### ISSUE TITLE
Rename pipeline phase `run` to `execute`

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1014]
This is just an aesthetics change so as to avoid weird constructs like the following:

```python
@rfm.run_before('run')
def do_sth(self):
    ...
```

**Comment by victorusu** [comment]
@vkarak, I did not understand if the change if to
```
@rfm.run_before('execute')
def do_sth(self):
    ...
```
or to 
```
@rfm.execute_before('run')
def do_sth(self):
    ...
```

PS: I agree that `run_before('run')` is strange. So, I am in favor of this change.

**Comment by vkarak** [comment]
@victorusu The first, `run_before('execute')`.

**Comment by victorusu** [comment]
@vkarak, this means that in the pipeline, we have to change the function from `run` to `execute`. Are we also changing `pre_run` and `post_run` to `pre_execute` and `post_execute`?

**Comment by vkarak** [comment]
@victorusu That's a very valid point and, honestly, I don't like the `pre_execute` and `post_execute`. I wasn't 100% sure of the change I have proposed in this issue, but this argument is decisive. The change would be much more disruptive than it seemed initially, so I suggest to drop this feature request. I can definitely live with `@run_before('run')`.

**Comment by teojgo** [comment]
@victorusu @vkarak we can rename the hooks to something like `inject_before`/`inject_after`.

**Comment by vkarak** [comment]
@teojgo Nooo! Way uglier than "run before run."
