### ISSUE TITLE
RFE: read Slurm `AdminComment` field during `sacct` queries

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#1019]
NERSC systems populate the Slurm [`AdminComment`](https://slurm.schedmd.com/scontrol.html) field in `sacct` queries with information about the job that ran. We would like to have a ReFrame test that ensures that this field is being populated correctly. However it seems that ReFrame ignores this field during its `sacct` queries while it waits for a job to finish.

Is it possible to capture this field, maybe with an optional flag (disabled by default, if that makes it less disruptive), and store the data in that field in a variable like `self.AdminComment` or something like that?

**Comment by bcfriesen** [comment]
Hi @vkarak - thanks for the quick reply! I will try your suggestion and let you know if it is sufficient.

Sorry I have been slow to test the MRs that you've created in response to my several RFEs recently; trying to catch up in the next few weeks.

**Comment by vkarak** [comment]
Sure, no problem!

**Comment by vkarak** [comment]
Hi @bcfriesen is this issue still relevant?

**Comment by bcfriesen** [comment]
Hi @vkarak, sorry I forgot about this issue - I think we have what we need, so this can be closed. Thanks!
