### ISSUE TITLE
Add a print sanity function

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1030]
It would be quite useful for debugging sanity expressions to have deferrable version of `print` that would print its arguments and then return them, so that you insert it anywhere in a sanity expression:

```python
self.sanity_patterns = sn.assert_eq(sn.count(sn.extract_all(...)), 10)

# print the extracted elements
self.sanity_patterns = sn.assert_eq(sn.count(sn.print(sn.extract_all(...))), 10)
```

**Comment by vkarak** [comment]
I have this ready, I am just waiting for #1050 to be merged. @teojgo Can you approve and merge it?

**Comment by teojgo** [comment]
@vkarak I merged it.
