### ISSUE TITLE
Make flexible node allocations work with the --exclude flag

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#104]
The scenario is having a test with `num_tasks = 0` and calling ReFrame with `--reservation=foo --exclude=[nodelist]`.

**Comment by teojgo** [comment]
If `num_tasks == 0` and a valid reservation is given, the actual `num_tasks` is set based on the reservation nodes satisfying the given partitions and constraints. Thus we must also check that a reservation node is not included in the nodelist given by the `--exclude` option. If it is, it must not count for the `num_tasks` that are calculated.
