### ISSUE TITLE
Add support for the LSF scheduler

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1055]
I got a couple of requests to implement support for the LSF scheduler. We could do a basic implementation as with PBS that we could test with the Slurm LSF wrappers.

**Comment by AnibalMG** [comment]
Any progress on this?

**Comment by vkarak** [comment]
Hi @AnibalMG, nothing so far. Our key focus has been in redesigning the configuration of the framework, which will unblock several other issues. I don't know about your bandwidth, whether you would like to contribute this backend. I could guide you through the necessary steps you need to do. It should not be difficult; we recently had an external contribution for a Torque backend in #1172.
