### ISSUE TITLE
Allow Syslog and Graylog handlers to dynamically set the address and port of the remote host

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1056]
Some sites would like to dynamically determine these parameters, for example, select the remote log server from a pool of servers or set it depending on where ReFrame is running.

@bcfriesen @brandongc I think this feature request will cover your needs. Settling on specific yaml file schema that defines the address and the port won't be as dynamic as you would like it to be.

**Comment by bcfriesen** [comment]
Yes this covers the NERSC use case. Thanks @vkarak!
