### ISSUE TITLE
test fail if 'src' directory is not present, even if no sources are required

### ISSUE THREAD

**Issue by boegel** [eth-cscs/reframe#1094]
When running tests that don't need any sources (`sourcepath` is left unspecified), they fail hard if no `src` directory is present (because that's the default value for `sourcesdir`).

```
  * Failing phase: run
  * Reason: pipeline error: virtual copying of files failed: [Errno 2] No such file or directory: '/tmp/test_reframe/src'
```

Either the non-existing `src` directory should be ignored if no sources are required for the test, or the default value for `sourcesdir` should be change to `None`?

**Comment by vkarak** [comment]
You should set `self.sourcesdir = None` and it will stop complaining :-)

**Comment by boegel** [comment]
OK, I can live with that, but it still feels a bit wrong to me...

When someone creates a test test that doesn't use any sources (for example a test running `echo hello`), they would run into this "`No such file or directory: '/tmp/test_reframe/src'`, which would make them go "WTF, I didn't specify this path anywhere".

**Comment by vkarak** [comment]
What it would probably make sense here is to have different defaults for normal `RegressionTest`s and `RunOnlyRegressionTest`. In the first one, you will most probably need to provide the source, whereas for the second one, you usually don't need it. The only thing is that this will break existing behaviour and thus tests.

**Comment by boegel** [comment]
Yeah, I understand that changing the default now may be difficult without breaking stuff for people.

But surely it can be avoided that tests fail because a directory where it plans to look for source files doesn't exist, but eventually doesn't need to check that directory at all because there are no source files?
