### ISSUE TITLE
Duplicated check path leads to error

### ISSUE THREAD

**Issue by mboisson** [eth-cscs/reframe#1119]
Hi,
I had aliased the search path with 
`alias reframe='reframe -C /cvmfs/soft.computecanada.ca/custom/reframe/config/settings.py -c /cvmfs/soft.computecanada.ca/custom/reframe/checks'` 

Then, I wanted to use just a subdirectory, so I used : 
`reframe -R -r -c /cvmfs/soft.computecanada.ca/custom/reframe/checks/advanced/osu` 

but it failed because it found a duplicate test (i.e. the same one) : 
```
Command line: /home/mboisson/.local/easybuild/software/2017/Core/reframe/2.21/bin/reframe -C /cvmfs/soft.computecanada.ca/custom/reframe/config/settings.py -c /cvmfs/soft.computecanada.ca/custom/reframe/checks -R -r -c /cvmfs/soft.computecanada.ca/custom/reframe/checks/advanced/osu
Reframe version: 2.21
Launched by user: mboisson
Launched on host: build-node.computecanada.ca
Reframe paths
=============
    Check prefix      :
(R) Check search path : '/cvmfs/soft.computecanada.ca/custom/reframe/checks:/cvmfs/soft.computecanada.ca/custom/reframe/checks/advanced/osu'
    Stage dir prefix     : /home/mboisson/tmp/reframe/stage/
    Output dir prefix    : /home/mboisson/tmp/reframe/output/
    Perf. logging prefix : /home/mboisson/tmp/reframe/perflogs
/home/mboisson/.local/easybuild/software/2017/Core/reframe/2.21/bin/reframe: /cvmfs/soft.computecanada.ca/custom/reframe/checks/advanced/osu/osu_benchmarks.py: test `OSULatencyTest' already defined in `/cvmfs/soft.computecanada.ca/custom/reframe/checks/advanced/osu/osu_benchmarks.py'
``` 

When there are multiple `-c` argument, it would be more intuitive to overwrite the previous value, rather than concatenate them ?

**Comment by vkarak** [comment]
Hi @mboisson, this is my bad when I suggested that before. I am quoting from the documentation:

> However, you can build your own check path by specifying multiple times the -c option. 

`-c` appends to the path. I agree perhaps we should make it accept paths in the form `path1:path2` etc. and if specified multiple times the latter override the previous ones.

**Comment by vkarak** [comment]
@teojgo We can fix that by ignoring duplicated paths in the check search path. If the `-R` options is passed, we should ignore entries in the path that are subdirectories of other components of the path.
