### ISSUE TITLE
Deprecate test syntax that overrides `RegressionTest` methods

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1130]

**Comment by ekouts** [comment]
@vkarak Do we want the deprecation warning only when the user overwrites a function from the pipeline, like `run` or `setup`, or when they try to overwrite any function of the `RegressionTest` object, like `depends_on`, `__str__` etc?

**Comment by vkarak** [comment]
Yes, I'd say so, but we would need another decorator to decorate a subclass that it actually extends the functionality. We don't want to ban overriding `RegressionTest`s functionality, but we want to discourage it for normal tests.

**Comment by ekouts** [comment]
In the PR for this issue or as a separate feature?

**Comment by vkarak** [comment]
No, in this one.
