### ISSUE TITLE
Print summary table and run options (optionally) for failures

### ISSUE THREAD

**Issue by ZQyou** [eth-cscs/reframe#1161]
@vkarak Let us discuss the detail of failure summary table here before I pull request. 

For summary table, here is an example:
```
SUMMARY OF FAILURES
------------------------------------------------------------------------------
[ .. skipped .. ]
------------------------------------------------------------------------------

Total number of tests: 669
Total number of failures: 39

Phase    #      Description
-------- ------ --------------------------------------------------------------
run      32     Failed to launch jobs
compile  6      Failed to compile the source code in the current environment
sanity   1      Failed in sanity checking
```
More precise description will be helpful for troubleshooting.

In my testing routine, I often convert the detail of failures to command-line options so I can rerun failed tests after fixing them. It is kind of like `--rerun-failed` in CTest. It is not common for others so I would like to make it optional:
```
$ reframe.py -t apps --rerun-failed -r
[ .. skipped .. ]

Total number of tests: 669
Total number of failures: 39

Phase    #      Description
-------- ------ --------------------------------------------------------------
run      32     Failed to launch jobs
                no module: -n openmpi_default_pgi -p pgi-default --system owens:login
                no module: -n openmpi_default_pgi -p pgi-default --system owens:pbs
                no module: -n openmpi_test_mpi_placement -p pgi-default --system owens:pbs
                no module: -n openmpi_module_path -p pgi-default --system owens:login
                no module: -n openmpi_module_path -p pgi-default --system owens:pbs
                run: -n darshan_mpi_test -p gnu-mvapich2 --system owens:pbs
[ .. skipped .. ]
```
Prepend a tag to the command-line options of a failure so one can decide if some failures can be skipped. 

The custom changes can be found here:

https://github.com/ZQyou/reframe/commit/8d969c4e130fed5d952c3d12f134afd0f4014b85#diff-4cc7123431b59755e1d77edbb2347fef (statistics.py)
https://github.com/ZQyou/reframe/commit/8d969c4e130fed5d952c3d12f134afd0f4014b85#diff-48e18b1d45e8fe87d74f3687c93fad73 (cli.py)

**Comment by vkarak** [comment]
Thanks @ZQyou! I'll have a look asap and get back to you.

**Comment by vkarak** [comment]
This is related to #1093 as well.

**Comment by vkarak** [comment]
I'd suggest to do WIP pull request in any case (mark with with `[wip]` in the title), so that we can comment directly on that. It'll be easier to keep track instead of commenting code inside the issue.
