### ISSUE TITLE
OrderedSet operations do not preserve order

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#1165]
Steps to reproduce:

```
s1 = OrderedSet('abcd')
s2 = OrderedSet('ca')
print(s1 - s2) # returns {d, b} instead of {b, d}
```

**Comment by vkarak** [comment]
The `==` is not correct either, because it compares as True for two sets with the same elements, but in different order.

**Comment by vkarak** [comment]
I think the equals correctly compares to `True`, since after all an OrderedSet is a set.

**Comment by vkarak** [comment]
@teojgo I'd suggest to do the minus manually in #1152 and we postpone this more general fix to the next sprint. It's not blocking by any means.
