### ISSUE TITLE
errexit global setting for job scripts

### ISSUE THREAD

**Issue by davidedelvento** [eth-cscs/reframe#1197]
Partially related with #1196 it would be nice if all job scripts automatically included `set -e` or `set -o errexit` to make sure that the job stops at the first failure (which then in #1196 could not be silently ignored, addressing the concern of the second bullet point).

I know I can use `@rfm.run_before` or making my own test class to avoid repeating that all the time, yet I think this would be a useful default to have.

**Comment by vkarak** [comment]
Fixed in #1490.
