### ISSUE TITLE
Enable bash login option per system partition

### ISSUE THREAD

**Issue by davidedelvento** [eth-cscs/reframe#1198]
In one of the partitions of my system, all jobs are required to have `-l` option in bash, as in `#!/bin/bash -l` (see [our documentation](https://www2.cisl.ucar.edu/resources/computational-systems/casper/example-scripts-casper-users)).

I see that the job scheduler and shell support that option (probably because of #882), but unfortunately the RegressionTest class does not 

https://github.com/eth-cscs/reframe/blob/d17ff88486096ef285727151ba3462146f54fc78/reframe/core/pipeline.py#L1212

That means that all ReFrame jobs submitted to that partition fail. Is this a feature that could get implemented?

**Comment by vkarak** [comment]
Hi @davidedelvento, in the past we used to always emit the `-l` option, but led to the bug in #997 which was fixed in #998. I will convert this to a feature request so as to give the possibility to enable this functionality per partition.
