### ISSUE TITLE
Add Travis CI test for Tmod and Lmod

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#120]

**Comment by victorusu** [comment]
It would be nice if we had the Travis definition like the one in [easybuilders](https://github.com/easybuilders/easybuild-framework/blob/master/.travis.yml). This defines the dependencies we need also for ReFrame.

Especially, this [file](https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/scripts/install_eb_dep.sh), which contains instructions on how to install LMod and TMod. In the script they have TMod version 3.2.10, but we should also install the latest TMod version.

**Comment by vkarak** [comment]
> In the script they have TMod version 3.2.10, but we should also install the latest TMod version.

It's good to test if the framework works fine with TMod 4.0, but I don't see it as a requirement for the moment.

**Comment by teojgo** [comment]
I think we could try to use their script as is. We can use the [`before_script`](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Projects-from-Source) to `wget` the script and then run it.

**Comment by vkarak** [comment]
@teojgo We should perhaps ask for permission to reuse it. What's the Easybuild license?

**Comment by vkarak** [comment]
This is now done with Github actions.
