### ISSUE TITLE
Unit test `TestAsynchronousExecutionPolicy.test_sigterm` fails randomly on master

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1216]
I think the unit test is not so robust. We should definitely revise it asap. Check here:

https://travis-ci.org/eth-cscs/reframe/branches?utm_medium=notification&utm_source=github_status

**Comment by vkarak** [comment]
@teojgo Still?

**Comment by teojgo** [comment]
Reopening since there was a failure of the test (https://travis-ci.org/eth-cscs/reframe/jobs/658635754?utm_medium=notification&utm_source=github_status)

**Comment by teojgo** [comment]
@vkarak yes and it's not easy to reproduce.

**Comment by vkarak** [comment]
Can you figure out how it failed this time?

**Comment by vkarak** [comment]
What if we set the handler at a global level in ReFrame and not just in the `Runner`?

**Comment by teojgo** [comment]
This time it fails due to `AssertionError: assert (1, 0) in {(0, 0), (1, 1)}`. Than means that the number of cases submitted was 1 and the number of failures 0.

**Comment by teojgo** [comment]
@vkarak I will investigate and do as you suggest.
