### ISSUE TITLE
AttributeError is raised in 'filternodes' method of slurm scheduler 

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#1258]
The exception is raised when `job.sched_access` is a `SequenceView` object and subsequent statements try to append values to an immutable object.

**Comment by vkarak** [comment]
Can you provide a trigger?

**Comment by teojgo** [comment]
If you combine `--flex-alloc-nodes=idle` with the `--partition=<my_partition>` cli options then https://github.com/eth-cscs/reframe/blob/cf09f724be9ccb53b8e4196195621ea09fa07881/reframe/core/schedulers/slurm.py#L234 is trying to mutate a `SequenceView` object.

**Comment by vkarak** [comment]
@teojgo Can you put a stack trace? It will help to understand what is happening and to fix this correctly.

**Comment by teojgo** [comment]
@vkarak, this happens during creation of the `Job` instance:
https://github.com/eth-cscs/reframe/blob/master/reframe/core/pipeline.py#L1019

since a SequenceView option is passed for the `sched_access`
