### ISSUE TITLE
Better formatting of the deprecation warning about pipeline methods overrides and more accurate message

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1263]
"reframe hooks" should be changed to "pipeline hooks" and we should consider coloring if possible.

```
/users/karakasv/Devel/reframe/cscs-checks/tools/profiling_and_debugging/notool.py:14: ReframeDeprecationWarning: 'JacobiNoToolHybrid.setup' attempts to override final method 'RegressionTest.setup'; consider using the reframe hooks instead
  class JacobiNoToolHybrid(rfm.RegressionTest):
/users/karakasv/Devel/reframe/cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py:14: ReframeDeprecationWarning: 'Ipm.setup' attempts to override final method 'RegressionTest.setup'; consider using the reframe hooks instead
  class Ipm(rfm.RegressionTest):
```

**Comment by ekouts** [comment]
@vkarak Do you want to colorize all deprecation warnings or this specific one?

Do you think `user_deprecation_warning` should be part of the `PrettyPrinter` (to get the colorize option) or should it get this option from somewhere else?

**Comment by vkarak** [comment]
>  Do you think user_deprecation_warning should be part of the PrettyPrinter (to get the colorize option) or should it get this option from somewhere else?

If coloring the message would require substantial refactoring, I would avoid it for the moment. I don't know what are the implications of this. Just moving this function to  the `PrettyPrinter` will break an implicit assumption in framework's design that a core component (here a core component raising a deprecation warning) may not call a frontend component (currently the `PrettyPrinter`). This is to enforce a separation of concepts. So, as of now, what you propose here, would mean to move the `PrettyPrinter` to `utility`, which I don't have problem to do. I would suggest, though, to open a different issue for allowing coloring the deprecation warnings, since it might not be as trivial as it seems.
