### ISSUE TITLE
More fine-grained control of job processes?

### ISSUE THREAD

**Issue by sjpb** [eth-cscs/reframe#1297]
If I want to specify that a task should run on all cores (or alternatively, sockets) of a system, how do I do that? I can set `num_tasks_per_core=1`, but I still have to set `num_tasks`, so I still need to know the number of cores.

Similarly, are there ways of controlling process placement for jobs, e.g. as provided by slurm via `sbatch --distribution` or openmpi via `mpirun --map-by` options and others?

**Comment by vkarak** [comment]
Hi @sjpb,

> If I want to specify that a task should run on all cores (or alternatively, sockets) of a system, how do I do that? I can set num_tasks_per_core=1, but I still have to set num_tasks, so I still need to know the number of cores.

Unfortunately, ReFrame does not collect such information from the system, so it won't set `num_tasks` for you. The only case when it will set `num_tasks` for you is if you want to submit a test on an unknown (or flexible) number of nodes (see [here](https://reframe-hpc.readthedocs.io/en/stable/running.html#controlling-the-flexible-node-allocation) for details),  but this a level up from what you are looking for.

> Similarly, are there ways of controlling process placement for jobs, e.g. as provided by slurm via sbatch --distribution or openmpi via mpirun --map-by options and others?

You cannot pass options to  the `sbatch` command  directly,  but  you can add any other option to the batch script itself as well as pass additional  options to the parallel  program launcher command. Here is a typical example:

```python
class MyTest(rfm.RegressionTest):
    @rfm.run_before('run')
    def add_sched_options(self):
        self.job.options = ['--distribution=xxx']


    @rfm.run_before('run')
    def add_launcher_options(self):
        self.job.launcher.options = ['--map-by=xxx']
```

For scheduler options in particular you may consider also using the [extra_resources](https://reframe-hpc.readthedocs.io/en/stable/reference.html#reframe.core.pipeline.RegressionTest.extra_resources).

**Comment by sjpb** [comment]
Thanks. It seems like system info would be a commonly-useful thing, especially in a performance test context where matching n_tasks to node sizes (or not) can be important. For slurm this info is easy to get - if you think there's an *obvious* reframe API for this let me know and once I've got our project working maybe I can push a PR back (won't be immediate!).

**Comment by vkarak** [comment]
> Thanks. It seems like system info would be a commonly-useful thing, especially in a performance test context

That's true. In fact, we have started thinking of what would be meaningful information for ReFrame to gather, but this project has been left a bit behind. Perhaps what you suggest here, focusing on the performance aspect only could be a first step. For this, though, I don't have an obvious API in mind, because I'm not sure at the moment what is the best approach for getting that information.

I will convert this issue to a feature request for future reference.

**Comment by vkarak** [comment]
ReFrame can now autodetect the processor topology of either local or remote partitions and makes this information available under `self.current_partition.proc`. Tests can use this information to adapt accordingly their setup. Check here for more information: https://reframe-hpc.readthedocs.io/en/stable/configure.html#auto-detecting-processor-information
