### ISSUE TITLE
CI's retry command does not affect all pipeline stages

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#130]
It seems that the `machineList` is ignored for the "Cleanup Stale" phase. Have a look here:

https://jenkins.cscs.ch/blue/organizations/jenkins/ReframeCI/detail/ReframeCI/93/pipeline/22

@teojgo If you think this can be solved quickly, we can schedule it for this sprint.

**Comment by teojgo** [comment]
@vkarak I did that on purpose, to execute the cleanup in all machines in any case, but I will fix it right now.

**Comment by vkarak** [comment]
ok, I see. I think's it's better for this stage to take into account the `machineList` as well, so as to avoid pipeline failures or stalls when a system is down.
