### ISSUE TITLE
RuntimeContext missing documented attributes

### ISSUE THREAD

**Issue by sjpb** [eth-cscs/reframe#1312]
Some useful info is documented here:
https://reframe-hpc.readthedocs.io/en/latest/reference.html#reframe.core.runtime.RuntimeContext

However after doing
```
from reframe.core.runtime import runtime
```

then either `runtime().output_prefix` or `runtime().stage_prefix` fails with AttributeError.

Looks like actually there's an undocumented `HostResources` object as `runtime().resources` which provides these attributes. Have I understood the docs or are they wrong?

version 3.0-dev6 (rev: b7d5b016)

**Comment by vkarak** [comment]
Thanks @sjpb for reporting. That's most probably a bug in the documentation. This part has been completely revised in #1242, so it seems that the documentation was not properly updated in that part.
