### ISSUE TITLE
Revisit deprecated features and options and consider removing them completely for 3.0

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1317]

**Comment by ekouts** [comment]
I found these deprecated features and options:

**Feautures**
- `evaluate` and `make_deferrable` in [deferrable.py](https://github.com/eth-cscs/reframe/blob/master/reframe/core/deferrable.py#L343)

- setting a timer field from a tuple
https://github.com/eth-cscs/reframe/blob/master/reframe/core/fields.py#L118
Btw in the `fields.py` there is a class `DeprecatedField` that is a wrapper for deprecating fields but it is not used anywhere besides the unittests.

- the old configuration
https://github.com/eth-cscs/reframe/blob/master/reframe/core/config.py#L207

- the override of final functions
https://github.com/eth-cscs/reframe/blob/master/reframe/core/meta.py#L51

**Options**
- `--flex-alloc-tasks`

- [scheduler-specific command-line options](https://github.com/eth-cscs/reframe/pull/1338)
Although this is still a PR so we should leave the deprecation warnings for a while

**Comment by vkarak** [comment]
Hi @ekouts, here is a list of what can be dropped:

> evaluate and make_deferrable in deferrable.py

Drop it now.

> setting a timer field from a tuple
https://github.com/eth-cscs/reframe/blob/master/reframe/core/fields.py#L118

Should be dropped either in 3.1 or 3.2, since the deprecation is introduced in 3.0

> the old configuration
https://github.com/eth-cscs/reframe/blob/master/reframe/core/config.py#L207

Will stay for some time, since it's breaking change.

> the override of final functions
https://github.com/eth-cscs/reframe/blob/master/reframe/core/meta.py#L51

Will stay for some time, since it's breaking change.

> scheduler-specific command-line options
Although this is still a PR so we should leave the deprecation warnings for a while

Should be dropped in either 3.1 or 3.2.

> --flex-alloc-tasks

Drop it now.

Can you create issues for the individual deprecations so that we remember to drop the features in future releases?

> Btw in the fields.py there is a class DeprecatedField that is a wrapper for deprecating fields but it is not used anywhere besides the unittests.

This is a useful wrapper for deprecating fields, like we did now with the `pre_run` et al.

**Comment by ekouts** [comment]
Ok, thanks for the feedback. Do you want to make new issues only for the ones we plan to drop in the future or the ones we are dropping now as well?

**Comment by vkarak** [comment]
@ekouts No, just for those to be dropped in the future.
