### ISSUE TITLE
copy only required src file in HelloWorldTest check

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#1322]
This is optional. There are a lot of files copied from
https://github.com/eth-cscs/reframe/tree/master/cscs-checks/prgenv/src
when for most checks only 1 file is needed. 
Would be nice to have only the required src copied OR clean a bit with something like:

> class HelloWorldTestMPI(HelloWorldBaseTest):
```python
        self.prebuild_cmd = [
            'cp %s mysrc' % self.sourcepath,
            'rm -f *.cpp *.c *.f90 *.txt *.cl *.ref',
            'mv src %s' % self.sourcepath,
        ]
```

**Comment by vkarak** [comment]
I think a cleaner solution would be to restructure the source directory by separating the sources in different subirectories. Then each check could set its `sourcesdir` accordingly. I think we do something similar with the profiling and debugging tools.

**Comment by jgphpc** [comment]
done with https://github.com/eth-cscs/reframe/pull/1370
