### ISSUE TITLE
Parallel testing

### ISSUE THREAD

**Issue by rsdmse** [eth-cscs/reframe#1329]
We're looking into ReFrame as a benchmark tool for our HPC maintenance. I wrote a script that performs a double loop over module version and GPU type, thanks to the parameterized_test examples included in the source. It works correctly, but the N_version x N_type steps are performed sequentially. I'm wondering if it's possible to submit the test jobs in parallel since they are all independent. I couldn't find anything in the docs, but perhaps I missed something obvious since the ReFrame jargon is new to me.

Of course as a workaround I could prepare a simple_test in ReFrame and write a wrapper to do the parallel job submission, but that would sort of defeat the purpose. We'd appreciate your advice.

Thanks in advance for any help.

**Comment by jgphpc** [comment]
Is this what you need ? 
https://reframe-hpc.readthedocs.io/en/stable/running.html?highlight=async#asynchronous-execution-of-regression-checks

**Comment by vkarak** [comment]
In addition to what @jgphpc has pointed to, you will need to set the `max_jobs` parameter in your partition configuration. By default, it’s 1. I take the point that we should highlight that better in the documentation or set the default to a value greater than one.

**Comment by rsdmse** [comment]
Thank you both for the help!
