### ISSUE TITLE
Add an option to reuse the existing stage directory

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1366]
For example, `--dont-restage`. If a stage dir exists, then this should be reused, else a a new one will be created as usual.

**Comment by teojgo** [comment]
@vkarak should this take into account retries?

**Comment by vkarak** [comment]
Yes, but what's the difference? If the test is retried it will reuse the same directory. I don't see a reason for this to have a different behaviour. Also the place where the directory is wiped out has nothing to do with the retries.

**Comment by teojgo** [comment]
The stage directory changes based on the retry index. so If the test is retried is will not take the stage dir of the previous retry.

**Comment by vkarak** [comment]
In that case, we could remove the suffix from the stage directory of the retries, but if this change breaks interfaces and assumptions in the code, we should discuss it further.

**Comment by vkarak** [comment]
@teojgo I think that option should simply reuse the original stage directory even for the retries, i.e., it should not create new stage directories for new retries.

**Comment by vkarak** [comment]
It turns out that the stage directory is wiped out in two places (perhaps, wrongly):

1. In `copytree()` [here](https://github.com/eth-cscs/reframe/blob/master/reframe/utility/os_ext.py#L108)
2. In `_makedirs()` [here](https://github.com/eth-cscs/reframe/blob/master/reframe/core/runtime.py#L39)

**Comment by vkarak** [comment]
I've done some further investigation. The first one in `copytree()` existed even from 2.4. The second was added later on and its purpose afaiu is to wipe out the output directory.
