### ISSUE TITLE
Optimize the imports in the entire source code

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#137]
In particular, the `reframe.settings` module is imported in:

* `reframe/frontend/executors/policies.py`
* `reframe/frontend/loader.py`
* `reframe/core/logging.py`
* `reframe/core/pipeline.py`

and is not used.

**Comment by vkarak** [comment]
It could certainly be. We should check for other stale imports, too.

**Comment by omlins** [comment]
There are also other stale imports. I will remove them all.
