### ISSUE TITLE
Logging does not take into account execution mode options

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#1379]
If an option affecting logging is passed in an execution mode, it is not taken into account.

**Comment by vkarak** [comment]
@teojgo Can you provide a reproducer and an analysis?

**Comment by teojgo** [comment]
Using the `--production` mode defined under `config/cscs.py` won't take into account the `--perflogdir` options since the update of the logging is done before, at https://github.com/eth-cscs/reframe/blob/8bf8e1ed42d1409bd55e4190efcc75c9e9134f47/reframe/frontend/cli.py#L421
