### ISSUE TITLE
Extend the @require_deps decorator to work better with parameterized tests

### ISSUE THREAD

**Issue by ekouts** [eth-cscs/reframe#1381]
It would be maybe useful to be able to pass the name of the class as a parameter to the decorated function and have access to all the parameterized tests (or maybe just the ones that the test depends on). If we implement this we should have a way to get the variant of the parameterized tests.

Not sure what is the best way to support dependencies on parameterized tests, this is just a suggestion.

**Comment by jjotero** [comment]
Is this for an external test depending on another test that is parameterized? Or is this for inter-parameter dependencies? For the first option, it sounds like passing a regex to `require_deps` would do the trick. For the second case, I think it would make more sense to extend the `parameter` directive.

**Comment by ekouts** [comment]
> Is this for an external test depending on another test that is parameterized? 

Almost, it is about an external test depending in many parameterized tests, with different parameters. In my case the user would want to do something like this:
```
steps = range(10)

@rfm.parameterized_test(*[[step] for step in steps])
class ComputeTest(rfm.RunOnlyRegressionTest):
...

testnames = [ f'MPI_ComputeTest_{step}' for step in steps ]

@rfm.simple_test
class AnotherTest(rfm.RunOnlyRegressionTest):
    def __init__(self):
        ...
        for test in testnames:
            self.depends_on(test)

    @rfm.require_deps
    def some_function(self, ComputeTest_0, ComputeTest_1, ...):
         # do something with all the ComputeTest testcases
```

This now is not very practical. We can use `[self.getdep(t) for t in testnames]` to get a list of the dependencies and use them in a different implementation of `some_function`, but maybe we could also extend `@rfm.require_deps` decorator. One idea it to work with the name of the test without parameters, `ComputeTest` in this case, and the argument becomes a ilst of Testcases that can be used in the method.

**Comment by jjotero** [comment]
Oh I see. I reckon that'd be a lot easier to implement this using the new parametrised tests with the `parameter` directive instead. With these, you have the full parameter space available as `cls.param_space`, where doing `iter(cls.param_space)` will give you the iterator that cycles through all the parameter combinations. From this, I think it should be easier to extend the `depends_on` method such that it adds all the dependencies on the test variants under the hood. With this approach, if I'm not mistaken (🧐😂), `require_deps` would just remain as is. 

The above python snippet would now look as follows:
```python

@rfm.simple_test
class ComputeTest(rfm.RunOnlyRegressionTest):
    parameter('step', *range(10))
    def __init__(self):
        ...


@rfm.simple_test
class AnotherTest(rfm.RunOnlyRegressionTest):
    def __init__(self):
        ...
        self.depends_on(ComputeTest)

    @rfm.require_deps
    def some_function(self, ComputeTest_0, ComputeTest_1, ...):
         # do something with all the ComputeTest testcases
```
Though, now that we have two supported methods for doing parametrised tests, I'm not sure what the plan is moving forward when implementing new functionalities.

**Comment by ekouts** [comment]
Sorry, I think I didn't explain well enough. What is not practical for me is more the definition of `def some_function(self, ComputeTest_0, ComputeTest_1, ...):` since you need to write all the testnames that you need. Afaik there is no way to write a loop with all the test names as arguments for `some_function`. I put only 10 which is doable but it could be many more, in a case that you want to collect all their outputs for example for some post processing. The way ReFrame supports this now is with the `getdep` method.
```python
    # No need for the decorator
    def some_function(self):
        for t in testnames:
            testcase = self.getdep(t) 
            # do something with all the ComputeTest testcases
```

If we consider this enough then this issue can be closed, but in the readthedocs reference we suggest that the @require_deps decorators should be preferred.

**Comment by vkarak** [comment]
Yep, we should I think.
