### ISSUE TITLE
Sanity function to check for empty error output

### ISSUE THREAD

**Issue by casparvl** [eth-cscs/reframe#1390]
I was creating a test in reframe, and hit a case where my sanity pattern was found in the output, yet there were also warnings going to `stderr`. Of course, if you expect a test to produce no warnings or errors, it makes a lot of sense to add a sanity check that checks if the error output is emtpy. I could however not find a default sanity test that does something like this...

Did I overlook it, or is it not implemented? If it isn't implemented, would it be an idea (feature request coming up here) to add such a sanity function? It seems like a pretty generic case one may want to check.

I now did

```
@sn.sanity_function
def assert_iostream_empty(iostream):
    return sn.assert_not_found(r'.+', iostream)
...
self.sanity_patterns = sn.all([
    assert_iostream_empty(self.stderr),
    ...
])
```

This seems to work, but I can imagine there may be more elegant methods (and maybe a more low level implementation of checking for an emtpy file than a generic regex is more robust too).

**Comment by vkarak** [comment]
Hi @casparvl, you can use `sn.assert_found(r'^$', self.stderr)` which match only when stderr is completely empty.

**Comment by casparvl** [comment]
Ah cool, that is indeed more robust.

By the way, I now also print the first part of the error output

```
@sn.sanity_function
def assert_file_empty(file):
    try:
        if sn.assert_not_found(r'^$', file):
            return True
    except SanityError:
        with open(file, 'r') as errorfile:
            errMsg = errorfile.read()
        raise SanityError("File {0} not empty.\nFirst 300 chars:\n{1}".format(file, errMsg[0:300])) from None
```
For me, printing a few lines from the error output really helps to quickly identify why the sanity check fails, making it a bit faster than having to browse to the file.

Anyway, thanks for the improved regex suggestion. It all works for me now, I just figured I'd share the idea in case you think it can help more people and want to implement it as something more standardized :)

**Comment by vkarak** [comment]
You can further simplify your sanity function by removing the `if`. All sanity function either return `True` or raise a `SanityError`. So you could simply do:

```python
try:
     return sn.assert_not_found(r'^$', file)
except SanityError:
    ...
```

**Comment by casparvl** [comment]
Hm, checking it further, I actually found

 ```
@sn.sanity_function
def assert_file_empty(file):
    try:
        if sn.assert_found(r'^$', file):
            return True
    except SanityError:
        with open(file, 'r') as errorfile:
            errMsg = errorfile.read()
        raise SanityError("File {0} not empty.\nFirst 300 chars:\n{1}".format(file, errMsg[0:300])) from None
```
not to work. (also tried without the if-statement, as you suggested)

I don't know why, because I agree with you that `^$` should match when the file is empty, which means `True` should be returned if the file is empty. Somehow, it ALWAYS matches, regardless of wheather the file is empty or not. Not sure how these regex matches go, but don't they go line by line? If so, then maybe `^$` just matches the last 'line' in a non-empty file or something...

Anyway, I found that your suggestion to leave the `if` out and return immediately the result of `sn.assert_not_found` actually works in the sense that I get the sanity error when the error file is not empty, but it prints the SanityError raised by `sn.assert_not_found` rather than my custom one. It seems the `except` somehow doesn't kick in if the error is raised on the line that `return`s. No idea why though, that doesn't make any sense to me.

In the end, I went back to the only thing that worked for me both in terms of throwing the sanity error at the right time, as well as with the right (custom) message:

```
@sn.sanity_function
def assert_file_empty(file):
    try:
        if sn.assert_found(r'.+', file):
            return True
    except SanityError:
        with open(file, 'r') as errorfile:
            errMsg = errorfile.read()
        raise SanityError("File {0} not empty.\nFirst 300 chars:\n{1}".format(file, errMsg[0:300])) from None
```

**Comment by vkarak** [comment]
> I don't know why, because I agree with you that ^$ should match when the file is empty, which means True should be returned if the file is empty. Somehow, it ALWAYS matches, regardless of wheather the file is empty or not. Not sure how these regex matches go, but don't they go line by line? If so, then maybe ^$ just matches the last 'line' in a non-empty file or something...

Indeed, regular expressions set the `re.MULTILINE` (we should document that...), so if  your file has an empty line my proposal will "fail.". You can however write the regex as `(?-m)^$`. This will disable the MULTILINE mode.

> Anyway, I found that your suggestion to leave the if out and return immediately the result of sn.assert_not_found actually works in the sense that I get the sanity error when the error file is not empty, but it prints the SanityError raised by sn.assert_not_found rather than my custom one

That's my bad, too. My example was faulty. To understand the reason why this is happening, have a look [here](https://reframe-hpc.readthedocs.io/en/stable/deferrables.html). TL;DR what happens is that your `return sn.assert_found(...)` line will not be evaluated in place. Instead your function returns a deferred expression. When ReFrame evaluates the `assert_file_empty()` function, it gets as a return value the sn.assert_found() deferred expression and it evaluates it. At this point you're essentially out of `assert_file_empty()` and therefore you can't catch the `SanityError`. To get around this, you have to force the evaluation of `sn.assert_found(...)` by either calling `sn.evaluate(expr)` or `expr.evaluate()`:

```python
@sn.sanity_function
def assert_file_empty(file):
   try:
       return sn.assert_found(r'(?-m)^$', file).evaluate()
   except SanityError:
       with open(file, 'r') as errorfile:
           errMsg = errorfile.read()
       raise SanityError("File {0} not empty.\nFirst 300 chars:\n{1}".format(file, errMsg[0:300])) from None
```

Generally, if you're inside a sanity function and you're not sure about the implicit evaluation rules, it's better if you explicitly evaluate any deferred expression. That's the only tricky part with the sanity functions. Let me know if this last proposal works for you.

**Comment by vkarak** [comment]
@casparvl Can I close this issue now?

**Comment by casparvl** [comment]
Yes, thanks! I will close it :)
