### ISSUE TITLE
Set default max_jobs > 1

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1391]
Otherwise the asynchronous policy acts like the serial one by default. The question is what should be a reasonable number. Could we make it unlimited by default?

**Comment by teojgo** [comment]
@vkarak Would it be possible to make it equal to the number of the regression tasks for the current run?

**Comment by vkarak** [comment]
What's the difference of that to "no limit"? We could conventionally set it to 0 to mean "unlimited."

**Comment by teojgo** [comment]
No real difference, just so that we don't have to add a convention.

**Comment by vkarak** [comment]
`0` or `None` should be fine as conventions.
