### ISSUE TITLE
Changes in `self.job.options` are inheritted in subsequent tests

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#1412]
Changes made in `self.job.options` made in one test case, propagate in subsequent tests. For example once the change in made here https://github.com/eth-cscs/reframe/blob/a83cb2142cbd7d40a78336e055f1b78f6a922eea/cscs-checks/system/slurm/slurm.py#L182 then the following tests will run using altered `job.options`. This seems to be the case since a change made to that test changes the `sched_options` field of the executor policy which was used during the task setup https://github.com/eth-cscs/reframe/blob/a83cb2142cbd7d40a78336e055f1b78f6a922eea/reframe/frontend/executors/policies.py#L64

**Comment by vkarak** [comment]
That's a major problem!

**Comment by vkarak** [comment]
Can you check when this was introduced?

**Comment by teojgo** [comment]
@vkarak I think that it was always there but it just surfaced because we added the `--account` job option in slurm tests.

**Comment by vkarak** [comment]
The fix should be easy. Just create a new list out of `sched_options`.

https://github.com/eth-cscs/reframe/blob/master/reframe/core/schedulers/__init__.py#L219
