### ISSUE TITLE
Add an interface for querying OS versions and flavors

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1420]
Similar to what we introduced for Cray's CLE in #1416, but more general, in order to cover other OSes.

**Comment by teojgo** [comment]
For additional information regarding the os version, kernel etc, the [platform](https://docs.python.org/3/library/platform.html#module-platform) python module can be used.

**Comment by vkarak** [comment]
I don't think that this is actually needed especially now that we add support for specifying features and extras in partitions and environments.
