### ISSUE TITLE
Error when reporting test failures

### ISSUE THREAD

**Issue by sjpb** [eth-cscs/reframe#1422]
After some test failures:
```shell
[  FAILED  ] Ran 52 test case(s) from 13 check(s) (6 failure(s))
```

I get this this traceback in reframe.log (not sure what's happened with the unprintable characters):

```shell
[2020-07-14T17:02:18] error: reframe: [31mreframe/bin/reframe: unexpected error: can only join an iterable
Traceback (most recent call last):
  File "$HOME/workingdir/reframe/reframe/frontend/cli.py", line 601, in main
    printer.info(runner.stats.failure_report())
  File "$HOME/workingdir/reframe/reframe/frontend/statistics.py", line 106, in failure_report
    reason += format_exception(*tf.exc_info)
  File "$HOME/workingdir/reframe/reframe/core/exceptions.py", line 294, in format_exception
    return 'value error: ' + format_user_frame(frame)
  File "$HOME/workingdir/reframe/reframe/core/exceptions.py", line 265, in format_user_frame
    exc_value, ''.join(frame.code_context))
TypeError: can only join an iterable
[0m
```

Let me know if there's anything I can to do get more info on what's not an iterable here! Maybe a None got returned??

**Comment by vkarak** [comment]
Hi @sjpb, it looks like the type of `code_context` has changed, but I'm not sure for the moment. Which Python version are you using?

**Comment by vkarak** [comment]
> Let me know if there's anything I can to do get more info on what's not an iterable here! Maybe a None got returned??

It could also be. But why?

> not sure what's happened with the unprintable characters

These are just the ASCII color codes.

**Comment by vkarak** [comment]
One thing that would help, if this error is reproducible, you can try printing the `frame.code_context` inside the `format_user_frame()` function.

**Comment by sjpb** [comment]
> Hi @sjpb, it looks like the type of `code_context` has changed, but I'm not sure for the moment. Which Python version are you using?

This is with Python 3.7.7. I'll update if I can get more info!

**Comment by vkarak** [comment]
@sjpb Are you calling somehow calling reframe interactively? Because then `frame.code_context` may be `None`, in which case, you would get this error.

**Comment by vkarak** [comment]
@sjpb Do you have more information on this one?

**Comment by sjpb** [comment]
No sorry - I modified the reframe code to log the object if it failed but I
haven't seen it happen again :-( I was running the normal way, i.e. letting
ReFrame find the tests.

**Comment by vkarak** [comment]
I don't know if you seen the last utility added to the framework regarding debugging? You can try the `util.repr()` to dump practically everything! You can even dump the whole ReFrame state if you call it on the `Runner` object :-) It helped us identify a very weird problem reported in #1369.

**Comment by vkarak** [comment]
Have you seen this problem again?

**Comment by sjpb** [comment]
No, I'm afraid not. Please feel free to close.

http://stackhpc.com/
Please note I work Tuesday to Friday.
