### ISSUE TITLE
Add possibility to skip tests from Python code

### ISSUE THREAD

**Issue by Madeeks** [eth-cscs/reframe#1474]
When writing a test about a feature which is only available from a certain version of a given application onwards, it would be a good thing to skip the test on old versions which do not support the feature, in order to avoid noise due to failures.
Currently the only documented ways to skip tests all take action from the ReFrame command line, using flags/options to filter tests based on name/PrgEnv/tags.
However, that requires to modify the CLI depending on the version of a tested software or on the environment variables currently loaded/mapped.

Would it be possible to have a way to skip a test from the ReFrame's Python API?
Having something like pytest's [skipping functions/decorators](https://docs.pytest.org/en/latest/skipping.html) would be great. Integrating packages like [semver](https://pypi.org/project/semver/) could also be an idea.
This way, tests could be self-sufficient in determining if they are suitable for a given application version, gracefully integrating into automated ReFrame runs.

**Comment by vkarak** [comment]
Thanks @Madeeks for your suggestion. It's a valid feature request. We need to understand though where and how would users like to skip a test? In your particular case, you need to run sth in the test's environment and decide what to do. That practically means that the test could be skipped anywhere in its pipeline, like the skip functions do in pytest. It also means that we need to add an easy way for users to execute in the environment that their test will execute. The API needs a bit of thinking, but we'll get to it.
