### ISSUE TITLE
Add option to disable JSON reporting completely

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1476]

**Comment by jgphpc** [comment]
We could have it on by default but instead of creating many report files:
```
~/.reframe/reports/run-report-0.json
~/.reframe/reports/run-report-1.json
etc...
```
we could set the default to overwrite:
```
~/.reframe/reports/run-report.json
```
and then add the option to specify new report files (as before) ?

**Comment by vkarak** [comment]
@jgphpc Not a bad idea either.

**Comment by vkarak** [comment]
I think that setting the default as you propose here is the best solution, in which case I don't think we need to have an extra configuration parameter to disable reporting completely, do we?

**Comment by jgphpc** [comment]
If you have hundreds of jobs all writing to the same file (~/.reframe/reports/run-report.json), it will not work, no ?

**Comment by vkarak** [comment]
Good point, but that's a different issue. Even if you had a single file per session as now, the problem would remain the same; you might end up with two reframe instances trying to create the same file. We would need to arbitrate that using a file lock.
