### ISSUE TITLE
Index out of range error when 'sourcesdir' does not exist

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#1504]
While working on writing an [example helloworld.py test using dependencies](https://gist.github.com/victorusu/78bb0f3b175be274a9d41d67a007bc54), I got the following [error](https://gist.github.com/victorusu/78bb0f3b175be274a9d41d67a007bc54#gistcomment-3473961).

For some reason that I do not understand (yet) only the `pgi` [tests have failed](https://gist.github.com/victorusu/78bb0f3b175be274a9d41d67a007bc54#gistcomment-3473963). 

But even though the failure is strange, I believe that ReFrame should not print the [stack trace in this way](https://gist.github.com/victorusu/78bb0f3b175be274a9d41d67a007bc54#gistcomment-3473961). It should be a bit more descriptive.

**Comment by vkarak** [comment]
The problem I see with your example is that your test has resources (see `sourcepath`), but you don't have them with your test. This might be causing (wrongly) ReFrame to crash. It should have simply failed. I will try to reproduce it with a simple example.

**Comment by vkarak** [comment]
I reproduced with a very simple test:

```python
@rfm.simple_test
class CompileOnlyHelloTest(rfm.CompileOnlyRegressionTest):
    def __init__(self):
        self.descr = 'Compile-only C Hello World test'

        # All available systems are supported
        self.valid_systems = ['*']
        self.valid_prog_environs = ['*']
        self.sourcesdir = 'does-not-exist'
        self.sourcepath = 'hello.c'
        self.sanity_patterns = sn.assert_not_found(r'(?i)error', self.stdout)
```

The problem is that the `sourcedir` does not exist and makes `osext.copytree()` crash.
