### ISSUE TITLE
Add line info when sanity fails

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#1536]
This code fails in sanity:

```python
import reframe as rfm
import reframe.utility.sanity as sn


@rfm.simple_test
class HelloTest(rfm.RunOnlyRegressionTest):
    def __init__(self):
        self.valid_systems = ['dom:login']
        self.valid_prog_environs = ['*']
        self.executable = 'echo x y'
        self.sanity_patterns = sn.all([
            sn.assert_found('x', self.stdout),
            sn.assert_eq(self.num_tasks, 0),
            sn.assert_found('z', self.stdout),
        ])
```

Sometimes, the message is explicit enough like in:

`sn.assert_found('z', self.stdout),` stops with:
  * Reason: sanity error: pattern `z' not found in `rfm_HelloTest_job.out'

but with:
`sn.assert_eq(self.num_tasks, 0),` stops with:
  * Reason: sanity error: 1 != 0

Would it be possible to have a message like:
  * Reason: sanity error: 1 != 0 (`2d sanity`)

**Comment by vkarak** [comment]
@jgphpc Can you be more precise as of what you would like to have?

**Comment by jgphpc** [comment]
pointing to which line in the python file would be enough for me.

**Comment by vkarak** [comment]
Do you know that you can pass a `msg` argument to the assert function and customize the actual message?

```python
            sn.assert_eq(self.num_tasks, 0, msg='num_tasks differ: {0} != {1}'),
```

This will print as a reason: `num_tasks differ: 1 != 0`.

Adding line info could be a possibility and we can see whether it's possible.

**Comment by jgphpc** [comment]
:+1:  I forgot about this, thanks!
