### ISSUE TITLE
Inconsistency in mode option passing 

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#1554]
If one runs reframe using the `-J` option inside the 

```python
    'modes': [
        {
          ...
                '-J reservation=maintenance',
          ...
            ]
        },
```

One gets the following job script

```bash
#!/bin/bash                                                                        
...                                                             
#SBATCH -- reservation=maintenance                                                 
...
```

However, if one submits thru the command line interface, then one gets the correct job script.

```bash
reframe  -n GromacsGPUCheck_small_maint -r -J reservation=maintenance
```

```
#!/bin/bash                                                                        
...
#SBATCH --reservation= maintenance                                                          
...
```

**Comment by rsarm** [comment]
I tried an example using `--mode` with
```
../../bin/reframe -r -c ulimit_check.py --prgenv PrgEnv-gnu --system dom:gpu -C ../../config/cscs.py --mode=maintenance
```
but it seems to set it right:
```
#SBATCH --reservation=maintenance
```
it fails with the error `sbatch: error: Batch job submission failed: Requested reservation is invalid` since there is no reservation with that name.

**Comment by vkarak** [comment]
Hi @rsarm, what you run is expected to be correct, because we have fixed the configuration file. The error reported here will appear as soon as you change the corresponding line in the configuration from `-Jreservation=maintenance` to `-J reservation=maintenance`.
