### ISSUE TITLE
Parameterized base tests and extensible parameterization of tests

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1567]
This was discussed in #1555, but I'm putting it as a separate issue, since it can be implemented as a stand-alone feature. The idea is to extend the notion of the parameterized test to base tests (not necessarily registered for running) , from which other concrete tests derive. To achieve this, we propose the use a `parameterize` directive at the class level that will act similarly to the current `@parameterized_test` decorator. Here is an example:

```python
class MyBaseTest(rfm.RegressionTest):
    parameterize('variant', str, ['cpu', 'gpu'])
    def __init__(self):
        ...

class MyTest(MyBaseTest):
    parameterize('scale', str, ['small', 'large'])
    def __init__(self):
        ...
        if self.variant == 'cpu' and self.scale == 'large':
            do_sth()
```

`MyTest` will be parametrized in two dimensions ('variant' and 'scale') leading to four actual tests. More functionality as the one suggested in #1555 can be incorporated to this directive.

**Comment by jjotero** [comment]
I've been doing some self brainstorming on this issue for the last few days, and I have a prototype implementation with the following functionality:
```python

class A(rfmTest):
    rfm_parameter('P0', [0, 1, 2, 3])

@rfm_test
class B(A):
    rfm_parameter('P1', [2.2])
    rfm_parameter('P0', [-1], inherit_values=True, filt_values = lambda x: x[:-1])

class C(B):
    rfm_parameter('P1', [4])

class D(rfmTest):
    rfm_parameter('P0', [90])

# class E(C,D):
#     pass      # ERROR: Multiple inheritance clash on P0

@rfm_test
class F(C):
    rfm_parameter('P0', []) # Make test an abstract test

class G(F,D):
    pass

# class H(G):
#     P0 = None # ERROR: Parameter P0 classes with the class variable P0

if __name__ == '__main__':
    # The base test
    A.show_parameter_space() # {'P0': [0, 1, 2, 3]}

    # Filtering on 'P0' and adding 'P1'
    B.show_parameter_space() # {'P0': [0, 1, 2, -1], 'P1': [2.2]}

    # Redefining 'P1'
    C.show_parameter_space() # {'P0': [0, 1, 2, -1], 'P1': [4]}

    # Another test with 'P0'
    D.show_parameter_space() # {'P0': [90]}

    # Multiple inheritance conflict error on 'P0'
    #E.show_parameter_space() # Doesn't work.

    # We can manually resolve this conflict. If we make C an abstract test by
    # setting 'P0' as undefined ...
    F.show_parameter_space() # {'P0': [], 'P1': [4]}
    # ... the multiple inheritance now works conflict free.
    G.show_parameter_space() # {'P0': [90], 'P1': [4]}

    # However, because F is an abstract test, it will fail if
    # we try to instantiate it
    # f = F() # Cannot instantiate an abstract test error.
```
Differently from the syntax suggested in #1555, the parameter inheritance, filtering and so on happens on a per-parameter basis. This means that if one were to have many parameters it could become a bit tedious to manually override the entire parameter space. For this reason, I'm thinking of also adding a new attribute `rfm_purge_paramters` that takes a list of the parameters to be purged as the sole argument. If no arguments are passed, I'd go for purging the full parameter space. Thoughts on this?
