### ISSUE TITLE
job submit limits don't count other user jobs that may already be in the queue

### ISSUE THREAD

**Issue by lagerhardt** [eth-cscs/reframe#1595]
We ran into an issue where it looks like the configurable "max_jobs" setting for a resource only looks at the jobs being submitted by the current instance of reframe. However, the user running reframe can have other jobs in the queue that could count against this limit. If they do, this will cause numerous test to fail with "QOSMaxSubmitJobPerUserLimit". It would be useful to have a flag that would expand this limit to all jobs in the queue that belong to a user.

**Comment by vkarak** [comment]
Hi @lagerhardt, thanks for reporting this. The `max_jobs` setting currently does not take into account any Slurm limits for the user. I will mark that as a feature request.

**Comment by ekouts** [comment]
I think the simplest way to handle this is to catch `QOSMaxSubmitJobPerUserLimit` from sbatch and when the jobs fails for this reason we put the task back to the `_ready_tasks` and try to submit it again later. I don't know whether we should have an extra attribute to the test that will allow for multiple submissions or whether we should always allow it.

**Comment by vkarak** [comment]
It might make sense to have a configuration parameter that will tell reframe to hold the test if it got such an error.
