### ISSUE TITLE
Check numerical sanity in CPMD test

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#161]

**Comment by rsarm** [comment]
@vkarak and @victorusu cpmd test already looks for the total energy as its sanity check. 

It uses `sn.assert_reference`, should  we change it to `sn.assert_lt(energy_difference, tol)` as we discussed before for other checks?

**Comment by vkarak** [comment]
@rsarm Yes, please go ahead and fix it as in the rest of the tests.
