### ISSUE TITLE
Update official Spack recipe to use the `./bootstrap.sh` script

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1616]

**Comment by victorusu** [comment]
The new ReFrame versions were already added to [Spack repo](https://github.com/spack/spack/blame/develop/var/spack/repos/builtin/packages/reframe/package.py)

What is left is if I have to modify it to use the `bootstrap` script or not...

**Comment by vkarak** [comment]
Since we can't use the system Python, then using the bootstrap script would make little difference. The only thing is that we should keep an eye on the python dependencies and update them in the Spack recipe.
