### ISSUE TITLE
Dependencies on parameterized tests

### ISSUE THREAD

**Issue by jjotero** [eth-cscs/reframe#1618]
Say that we have a run-only test that depends on a compile-only test. If one wanted to extend that compile-only test as a parameterized test (e.g. to test multiple compilation options), it would be nice if we could write such scenario as follows:
```python
@rfm.parameterized_test(['P0'], ['P1'])
class A(rfm.CompileOnlyRegressionTest):
    def __init__(self, param):
        ...


@rfm.simple_test
class B(rfm.RunOnlyRegressionTest):
    def __init__(self):
        self.depends_on('A')
```
This code would register 2 compile-only tests (one for each of the parameters), and a run-only test for each of the compile-only tests. 

Actually, using the syntax to be introduced by #1614 (and later changed in #1699), we could go even further and do
```python
@rfm.simple_test
class A(rfm.CompileOnlyRegressionTest):
    def __init__(self):
        param = parameter(['P0', 'P1'])
        ...

@rfm.simple_test
class B(rfm.RunOnlyRegressionTest):
    def __init__(self):
        self.depends_on('A')


@rfm.simple_test
class C(rfm.RunOnlyRegressionTest):
    def __init__(self):
        self.depends_on('A', when={'param': lambda x: x!='P0'})

```
where `C` would only depend on A when the lambda associated to `param` returns true.

**Comment by vkarak** [comment]
We should perhaps consider this in relation to #1381.

**Comment by jjotero** [comment]
I also see a strong link between this one and #1577.

**Comment by vkarak** [comment]
Will be covered by #1577.
