### ISSUE TITLE
module-path=+<path> conflict with module collections

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#1631]
I believe there is a conflict between `--module-path` and lmod `module restore`.
This check:

```python
import reframe as rfm
import reframe.utility.sanity as sn


@rfm.simple_test
class HelloTest(rfm.CompileOnlyRegressionTest):
    def __init__(self):
        self.valid_systems = ['pilatus:login']
        self.valid_prog_environs = ['*']
        self.sourcepath = 'hello.c'
        self.modules = ['ddt']
```

when run with:
> ~/reframe.git/bin/reframe -C ~/reframe.git/config/cscs.py -c jg.py -r -p PrgEnv-cray \
`--module-path=+/apps/eiger/UES/tools/easybuild/modules/all`

fails with (attached log):
```
  * Reason: environ error: could not execute module operation: command '/usr/share/lmod/lmod/libexec/lmod python show ddt' failed with exit code 1:
```

**Comment by jgphpc** [comment]
[eff.log](https://github.com/eth-cscs/reframe/files/5622917/eff.log)

**Comment by jgphpc** [comment]
My guess is that `restore` unsets the modulepath:
```
(myvenv) # piccinal@uan04|~$  mo use /apps/eiger/UES/tools/easybuild/modules/all
(myvenv) # piccinal@uan04|~$  ma ddt
   ddt/20.0-Suse-15.0    ddt/20.1.1-Suse-15.0 (D)
```
:ok:
 
```
:-1: 
(myvenv) # piccinal@uan04|~$  mo restore PrgEnv-cray
Restoring modules from user's PrgEnv-cray
(myvenv) # piccinal@uan04|~$  ma ddt
No module(s) or extension(s) found!
```

**Comment by teojgo** [comment]
As @jgphpc wrote above, the problem comes from the `restore`:
https://github.com/eth-cscs/reframe/blob/1897374c811339b0a7bbe4b9982bdfb5222662d7/reframe/core/modules.py#L870

Before the restoration, the `MODULEPATH` contains the path added via the `--module-path` cli option. After executing the `restore` module command though, the additional module path is not contained in the `MODULEPATH` anymore.

**Comment by vkarak** [comment]
Indeed, that's the behaviour of `module restore`. I guess that we will need to keep track of the module path components that we have added and then add them again after the `restore`.
