### ISSUE TITLE
Environment variables are not resolved for `--perflogdir`

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#1638]
This happens in the `production` mode were the `--perflogdir` contains environment variables

**Comment by vkarak** [comment]
It seems that environment variables are not expanded at all.

**Comment by vkarak** [comment]
This seems to be present before 3.1!

**Comment by vkarak** [comment]
This is broken from this commit: 7430d183403ceab3f2ba2ba97e4340f8bef3c702

**Comment by vkarak** [comment]
Lowering priority since this existed for so long and it did not impact us. But we should solve it in 3.4.
