### ISSUE TITLE
Preserving symlinks in sources directories creates dangling symlinks in the staging directories

### ISSUE THREAD

**Issue by jjotero** [eth-cscs/reframe#1639]
#1580 introduced in reframe the default behaviour of copying symlinks onto the stage directory as symlinks rather than copying the content of the directory that the symlink points to. This works fine when the symlink points to another file that is under the same directory tree. However, this will create dangling symlinks if the original link pointed to a file/directory outside this directory tree.

In reframe, this could happen when a test case needs resources defined in another test.

**Comment by teojgo** [comment]
We could do one of the following:
* Perform the copy, check for broken symlinks and perform a copy of the actual file (without respecting the symlink).
* Find out which links are going to be broken, ignore them in the first copy and then those copy manually without respecting the symlink.

**Comment by jjotero** [comment]
Why not simply reverting #1580? Did this PR introduce any functionality that can't be achieved by marking the symlinks to be preserved in the reframe tests with `self.readonly_files`?

**Comment by teojgo** [comment]
@jjotero Yeah we can do this, or have another option whether to follow symlinks on the src directory or not.

**Comment by jjotero** [comment]
If there isn't any scenario that breaks if #1580 is reverted, I think that'd be the cleanest (and also the easiest) solution. Regarding the option of treating symlinks inside `src` differently to symlinks elsewhere, I have the feeling that such changes might open other fronts for potential bugs.

**Comment by jgphpc** [comment]
At the time, I did not know about `self.readonly_files`. 
I am ok with reverting.
