### ISSUE TITLE
Can't use check_name in perflog prefix any more

### ISSUE THREAD

**Issue by sjpb** [eth-cscs/reframe#1650]
Releases after v3.2 using `%(check_name)s` in the perflog handler prefix fails performance phase with:

    Reason: logging error: logging failed: unknown placeholder in filename pattern: 'check_name'

**Comment by vkarak** [comment]
Hi @sjpb, can you share your `handlers_perflog` configuration entry? Do you see that also in master?

**Comment by sjpb** [comment]
```
'handlers_perflog': [
                {
                    'type': 'filelog',
                    # make this the same as output filenames which are ('sysname', 'partition', 'environ', 'testname', 'filename')
                    'prefix': '%(check_system)s/%(check_partition)s/%(check_environ)s/%(check_name)s', # <testname>.log gets appended
                    'level': 'info',
                    # added units here - see Reference: https://reframe-hpc.readthedocs.io/en/latest/config_reference.html?highlight=perflog#logging-.handlers_perflog
                    'format': '%(check_job_completion_time)s|reframe %(version)s|%(check_info)s|jobid=%(check_jobid)s|%(check_perf_var)s=%(check_perf_value)s|%(check_perf_unit)s|ref=%(check_perf_ref)s (l=%(check_perf_lower_thres)s, u=%(check_perf_upper_thres)s)|%(check_tags)s',  # noqa: E501
                    'datefmt': '%FT%T%:z',
                    'append': True
                }
            ]
```

I did see it on master I think at `6b28d4f1db002b556f0368fc4944794256df2913`, worked backwards through releases till I found one which worked because I knew it used to!

**Comment by sjpb** [comment]
Agh I just did a pull now HEAD works ok. Guess it was that logging commit that landed, bad timing!

**Comment by vkarak** [comment]
I could reproduced this in ReFrame 3.3, but it is fixed in current master. The problem comes from the fact that you were using `check_name` in the `prefix` of the perflog handler.
