### ISSUE TITLE
Provide a way to tests to specify the ReFrame version that they require

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#166]
Since we are actively developing the framework, adding new features, deprecating and removing older stuff, it would be good to have a way in a regression test to specify the version(s) of ReFrame that can run it. During loading, ReFrame will simply ignore incompatible tests.

@eth-cscs/reframe-devteam What do you think?

**Comment by teojgo** [comment]
A field might be added to the `RegressionTest` class, like `self.min_reframe_version` that would default to None indicating that the test can run with all versions. The tests that set this field would be omitted if a version is the version of ReFrame running the test is less that the required one.

**Comment by vkarak** [comment]
I don't want just the minimum version, but sth more flexible. One that would allow to specify also minimum, maximum or both.

**Comment by vkarak** [comment]
Moving to the next sprint, since it depends on #264. The version validation must happen at the import time, so it should be integrated with the class decorators that register a test for running.
