### ISSUE TITLE
Generate executable `_job.sh` files

### ISSUE THREAD

**Issue by homerdin** [eth-cscs/reframe#1679]
It would be useful to have a configuration setting to generate `_job.sh` files that are executable.  Would this be a potential feature that could be added?

Thanks

**Comment by vkarak** [comment]
Hi @homerdin, yes it should be an easy addition. Thanks for the suggestion.

**Comment by jgphpc** [comment]
@vkarak where is
https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/executors/__init__.py#L270
defined ?

**Comment by teojgo** [comment]
> @vkarak where is
> `compile` in https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/executors/__init__.py#L270
> defined ?

https://github.com/eth-cscs/reframe/blob/13c372ef7aa5d63f6d74c73f61c4c033c0312d53/reframe/frontend/executors/__init__.py#L226

**Comment by teojgo** [comment]
@jg The `compile` of the check, it is defined here: https://github.com/eth-cscs/reframe/blob/13c372ef7aa5d63f6d74c73f61c4c033c0312d53/reframe/core/pipeline.py#L1165

**Comment by vkarak** [comment]
@jgphpc Actually the building phase where @teojgo pointed you has nothing to do with the job script creation. The job script is created by the `ShellScriptGenerator` here:

https://github.com/eth-cscs/reframe/blob/master/reframe/core/shell.py#L114

Currently, setting the executable bit is handled by the scheduler backends (only the `local` scheduler does that):

https://github.com/eth-cscs/reframe/blob/master/reframe/core/schedulers/local.py#L63-L64

I think the best solution is to move that responsibility to the shell script generator by adding an option that controls whether to set `+x` or not. And then we remove this logic from the local backend, which is just a leftover from the past.
