### ISSUE TITLE
Single-char scheduler options passed through `-J` are not handled properly

### ISSUE THREAD

**Issue by rsarm** [eth-cscs/reframe#1693]
[Here](https://github.com/eth-cscs/reframe/blob/d56e435acb4373447021b29ac4eb707165c09a81/reframe/frontend/cli.py#L905-L911) `opt` is the complete option (something like `A=usup`), not just the flag. The length is not 1, then it never goes to the `elif len(opt) == 1` resulting in adding two minuses (`--A`) when it should be a single one (`-A`):
```
        for opt in options.job_options:
            if opt.startswith('-') or opt.startswith('#'):
                parsed_job_options.append(opt)
            elif len(opt) == 1:
                parsed_job_options.append(f'-{opt}')
            else:
                parsed_job_options.append(f'--{opt}')
```

**Comment by rsarm** [comment]
I think here we can have options that are `flag foo=bar`,  `flag=foo=bar`, `flag='foo bar'` and `flag 'foo bar'`. That can make the parser for knowing when to add `-` or `--` a bit complicated. I think reframe should pass the options verbatim to the job script: `-J='#BATCH --flag foo'` or `-J='--flag foo'` and drop the support for adding `-` or `--`. What do think @vkarak?

**Comment by vkarak** [comment]
@rsarm Can you pass `-A=usup` to Slurm or does it have to be `-A usup` or `--account=usup`. I think the `-A=usup` is not POSIX compliant.

**Comment by vkarak** [comment]
I think what is problematic there is the `len(opt) == 1`. We should split `opt` on `=` or a space and then check. Something like this:

```python
        for opt in options.job_options:
            optstr = re.split(r'=|\s+', opt, maxsplit=1)
            if opt.startswith('-') or opt.startswith('#'):
                parsed_job_options.append(opt)
            elif len(optstr) == 1:
                parsed_job_options.append(f'-{opt}')
            else:
                parsed_job_options.append(f'--{opt}')
```
