### ISSUE TITLE
"Rerun with" advisory error message is a bit unclear

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#1703]
A NERSC staffer was a bit confused today when trying to run a particular ReFrame test and ReFrame responded with the error message:

```
[2021-01-21T16:48:22-08:00]   * Rerun with '-n <...> -p PrgEnv-intel --system <...>'
```

However, if one copies+pastes exactly what is in that error message, it fails again because the message does not recommend the `-r` flag. It was simple to fix, but seems like the error message should include the `-r` flag since it says `Rerun with ...`.

What do you think?

**Comment by victorusu** [comment]
Thanks for reporting this.
We will fix it.

**Comment by vkarak** [comment]
Thanks @bcfriesen, good catch!

**Comment by bcfriesen** [comment]
Thanks @victorusu and @vkarak !
