### ISSUE TITLE
ReFrame Docco: Running the Unit Test doesn't work in a EB installed setup.

### ISSUE THREAD

**Issue by akesandgren** [eth-cscs/reframe#1724]
Running the Unit Test doesn't work in a EB installed setup, there is no test_reframe.py in there.

May be the same problem with a Spack installation.

**Comment by teojgo** [comment]
@akesandgren we did not include the testsuite on purpose. Do you think it should be included? In general, if you want to include the tests you can clone the repo directly, use the bootstrap script and test. This is the case if you want to introduce a change and rerun the tests.

**Comment by akesandgren** [comment]
I was just following the install instructions (not the EB instructions but still using an EB install) and tried to use it.
If it's not supposed to be there then it's fine.

Docco should perhaps mention that it's only available when installing from git clone?

**Comment by vkarak** [comment]
I think it's correct to change the documentation only. I will probably remove completely the "Running the unit tests" section. I might move it on README, since it's not necessarily user documentation.
