### ISSUE TITLE
ReFrame tutorial: missing -pthread in A Multithreaded “Hello, World!”

### ISSUE THREAD

**Issue by akesandgren** [eth-cscs/reframe#1726]
The initial Multithreaded “Hello, World!” most likely need a "-pthread" compiler flag. It is at least required for g++ 9.3.0.

Without it I get:
```
cat stage/generic/default/builtin/HelloThreadedTest/rfm_HelloThreadedTest_build.err 
/scratch/cc0LAYZw.o:hello_threads.cpp:function std::thread::thread<void (&)(int), int&, void>(void (&)(int), int&): error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
```

**Comment by vkarak** [comment]
@akesandgren I don't know if this is a "bug." The tutorial examples are not entirely generic and need to be slightly adapted to each system. We're testing them continuously on Daint, but of course, this doesn't make them generic. Nonetheless, adding `-pthread` also in the examples might be harmless.

**Comment by akesandgren** [comment]
Adding -pthread would make it more (linux) generic since that's what a standard gcc requires, but it might require a comment that non-gcc (xlc, pgcc for instance) will have problem with it.

**Comment by vkarak** [comment]
Actually, I think the Cray wrappers do add the `-pthread` for you to keep things "simple" :-)
