### ISSUE TITLE
Problem with EasyBuild installed ReFrame and a user settings.py without a 'logging' section

### ISSUE THREAD

**Issue by akesandgren** [eth-cscs/reframe#1727]
Installed ReFrame/3.4 with EasyBuild (but since my system only have Python3.5 I've modified the original easyconfig to depend on GCCcore/9.3.0 and Python/3.8.2)

Add a $HOME/.reframe/settings.py with only a 'systems' and a 'environments' section, i.e. 'logging' is missing.

Running
```
reframe -c $EBROOTREFRAME/tutorials/basics/hello/hello1.py -r
```
I get
```
/home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/ReFrame/3.4-Python-3.8.2/bin/reframe: failed to load configuration: could not validate configuration file: '/home/a/ake/.reframe/settings.py': 'logging' is a required property
```

@vkarak asked me to submit an issue on this.

**Comment by teojgo** [comment]
Should we remove the `logging` from the required sections?

**Comment by teojgo** [comment]
I think we can close this, since it is expected because `logging` is required. Is it ok for you @akesandgren ?
