### ISSUE TITLE
Unexpected dereferenced symlinks in output and reports.

### ISSUE THREAD

**Issue by akesandgren** [eth-cscs/reframe#1728]
EaysBuild installed Reframe 3.4

```
cd /proj/nobackup/support-hpc2n/ake/reframe-testing
reframe -r -c $EBROOTREFRAME/tutorials/basics/stream/stream2.py --performance-report
[ReFrame Setup]
  version:           3.4
  command:           '/home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/ReFrame/3.4-Python-3.8.2/bin/reframe -r -c /home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/ReFrame/3.4-Python-3.8.2/tutorials/basics/stream/stream2.py --performance-report'
  launched by:       ake@b-an02.hpc2n.umu.se
  working directory: '/pfs/proj/nobackup/fs/projnb10/support-hpc2n/ake/reframe-testing'
  settings file:     '/home/a/ake/.reframe/settings.py'
  check search path: '/pfs/stor10/users/home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/ReFrame/3.4-Python-3.8.2/tutorials/basics/stream/stream2.py'
  stage directory:   '/pfs/proj/nobackup/fs/projnb10/support-hpc2n/ake/reframe-testing/stage'
  output directory:  '/pfs/proj/nobackup/fs/projnb10/support-hpc2n/ake/reframe-testing/output'
```
I expect the working, stage, and output dirs to be "/proj/nobackup/support-hpc2n/ake/reframe-testing/..." not the above.

FYI, /proj/nobackup/support-hpc2n is a symlink to /pfs/proj/nobackup/fs/projnb10/support-hpc2n

**Comment by akesandgren** [comment]
And the same for the run-report.json

**Comment by teojgo** [comment]
I don't know if there is a simple fix for this since the `os.path` family of functions dereference the symbolic links. Even for the current working directory, the links are dereferenced.

**Comment by vkarak** [comment]
I agree with @teojgo and workarounds such as [this](https://stackoverflow.com/questions/123958/how-to-get-set-logical-directory-path-in-python), I don't like them.

**Comment by akesandgren** [comment]
Yeah, I keep forgetting that getcwd(2) does that...
