### ISSUE TITLE
self.build_locally = False doesn't get a --time specification with Slurm based launching.

### ISSUE THREAD

**Issue by akesandgren** [eth-cscs/reframe#1733]
using this config:
```
site_configuration = {
    'systems': [
        {   
            'name': 'kebnekaise',
            'descr': 'Kebnekaise cluster',
            'hostnames': ['b-'],
            'modules_system': 'lmod',
            'partitions': [
                {   
                    'name': 'bdw',
                    'descr': 'Broadwell compute nodes',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'access': ['-C broadwell', '-A sysop'],
                    'environs': ['gnu', 'intel'],
                    'resources': [
                        {   
                            'name': 'tasks',
                            'options': ['-n {cores}']
                        },
                    ],
                },
...
}
```
And a test that does
```
self.build_locally = False
```
The build phase created slurm batch file lacks a --time specification, causing it to fail on our system since we require it to be specified.

**Comment by teojgo** [comment]
@vkarak do you think we should add an extra field for the timelimit of the build or use the same as the one of the running job?

**Comment by vkarak** [comment]
I would use the same or make it indefinite or expose the `build_job` to the users. Because the problem of taking the job limit of the run job is that it might be completely irrelevant, but on the other hand I don't want to replicate everything for the build job.

**Comment by akesandgren** [comment]
indefinite would cause problems for site with a upper limit on time/job.

**Comment by vkarak** [comment]
Well, I mean "indefinite." I am inclined in removing completely the default limit imposed by the framework on the test. The fact that users *must* pass `--time` when running on a specific partition, I think that it should be reflected in the partition configuration. Either in the `access` option or a new option, so as to cover also the `local` scheduler. The default time limit in Slurm is that of the partition, as defined by the sysadmins. You would still be able to set the `time_limit` inside your tests also for the generated build jobs.

**Comment by akesandgren** [comment]
Well we don't have a default, --time must be explicitly set. So please make sure it's easy yo handle someway.

**Comment by vkarak** [comment]
Would you be happy to define it in the configuration?

**Comment by akesandgren** [comment]
well a default there would do, but you need to be able to specify it per test. some build jobs may take a very long time...

**Comment by vkarak** [comment]
Yes, you will be able to do that, too.
