### ISSUE TITLE
Print first N lines of a failed build's stderr

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1735]
Now we request users to always go and look into the stored stderr. It'd be more convenient if we printed the first N lines (N could be configurable).

**Comment by teojgo** [comment]
We could use something like that: https://docs.python.org/3/library/reprlib.html#module-reprlib to handle the representation of the error message and print the initial lines.

**Comment by vkarak** [comment]
I don't think we need `reprlib` and all the machinery around it. We do have the output already, we simply need the first N lines.
