### ISSUE TITLE
Install issue - argcomplete and pyyaml not installed when using pip install

### ISSUE THREAD

**Issue by branfosj** [eth-cscs/reframe#1766]
I install ReFrame into a virtualenv, using `pip install`. With v3.4 this is fine. However, with v3.4.1 this is broken, as `argcomplete` and `pyyaml` are not automatically installed.

Error message is:
```
ModuleNotFoundError: No module named 'argcomplete'
```

**Comment by vkarak** [comment]
Thanks @branfosj for reporting!
