### ISSUE TITLE
Make the `@required_version` decorator a built-in

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1797]
The `@required_version` decorator is an interesting tool to have ReFrame skip incompatible tests. Although we currently don't use it so much, it will become more relevant when we start creating test libraries and tests may be run by different ReFrame versions that may or may not support some features that the test require. The problem with the decorator now is that it is executed too late, i.e., after the class creation, so we couldn't capture features like the pipeline hooks when they were added. Therefore, I suggest making a  built-in, such as the `variable()` and `parameter()`, which execute even before the class body is executed.

**Comment by jjotero** [comment]
Would it make sense to set this through the `__init_subclass__` hook instead?
```python
class Foo(rfm.RegressionTest, required_version=[x.x.x, y.y.y]):
   ...
```
To me, this feels more natural than having something in the class body like
```python
class Bar(Foo):
    required_version(x.x.x, y.y.y)
    def __init__(self):
        ...
```
That way we can leave the class body for more common python-like assignments as done with the `variable` or `parameter` built-ins.

**Comment by vkarak** [comment]
I've no problem where it fits best. The current problem is that the decorator can only cover a small set of features. Also we are free to choose a better name.
