### ISSUE TITLE
No autocompletion available when installed via Spack

### ISSUE THREAD

**Issue by sjpb** [eth-cscs/reframe#1835]
Following the getting started guide https://reframe-hpc.readthedocs.io/en/stable/started.html#enabling-auto-completion it states there should be autocompletion scripts under `<install_prefix>/share/completions/reframe.<shell>`.

Spack shows:
```shell
$ spack find -p reframe
==> 1 installed package
-- linux-centos8-sandybridge / gcc@9.3.0 ------------------------
reframe@3.4  /nopt/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/reframe-3.4-rkbham2eyv3cy7fpot7ljf7eejjnjtc7
```

But there's no `share/` directory I can find in there?

**Comment by vkarak** [comment]
Hi @sjpb auto-completion was introduced in 3.4.1 and updated in 3.4.2. The Spack repo has only up to 3.4, unfortunately. We need to update the recipes there.

**Comment by vkarak** [comment]
@sjpb ReFrame 3.4.1 and 3.4.2 have just been merged into Spack.
