### ISSUE TITLE
Remove custom bits from netCDF tests

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#185]
We have a combined read/write example. To publish the test we will need to use two separate read/write tests perhaps.

**Comment by jgphpc** [comment]
using /apps/common/UES/reframe/resources/netcdf/

**Comment by vkarak** [comment]
@jgphpc I think this should transferred internally. It's something that we should fix.

**Comment by jgphpc** [comment]
moved to https://jira.cscs.ch/browse/UES-1294
