### ISSUE TITLE
Introduce a new test variable that combines `valid_systems` and `valid_prog_environs`

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1852]
It is very common to see the following pattern inside tests:

```python
        if self.current_system.name in ['daint', 'dom']:
            self.valid_prog_environs = ['PrgEnv-gnu', 'PrgEnv-intel']
        elif self.current_system.name in ['arolla', 'tsa']:
            self.valid_prog_environs = ['PrgEnv-gnu-nompi']
        elif self.current_system.name in ['eiger', 'pilatus']:
            self.valid_prog_environs = ['PrgEnv-gnu']
        else:
            self.valid_prog_environs = []
```

The alternative way to write this is to define a dictionary and do manually the lookup. I would suggest that this alternative syntax is supported by the framework directly, so that somebody could rewrite the above as follows:

```python
        self.valid_environs = {
            ('daint', 'dom'): ['PrgEnv-gnu', 'PrgEnv-intel'],
            ('arolla', 'tsa'): ['PrgEnv-gnu-nompi'],
            ('eiger', 'pilatus'): ['PrgEnv-gnu']
        }
```

And this could also be defined in the class body as well:

```python
class MyTest(rfm.RegressionTest):
    valid_environs = {
        ('daint', 'dom'): ['PrgEnv-gnu', 'PrgEnv-intel'],
        ('arolla', 'tsa'): ['PrgEnv-gnu-nompi'],
        ('eiger', 'pilatus'): ['PrgEnv-gnu']
    }
```

To implement this, I think we need #1474 to be able to skip tests dynamically, so that we could skip the tests in a pre-setup phase if the filtering is per partition. But if only systems are present as keys, then I think that the filtering should take place just after `__init__`, so that we keep the current behaviour. Also instead of tuples as keys, we could have strings, despite some duplication, since it could potentially be simpler implementing. I don't know if that would deprecate the `valid_systems` and `valid_prog_environs`, because these two act combinatorically: the test is valid for the external product of the two (filtered out by which environments are defined for each partition). And I also don't know whether we need to introduce with this syntax the concept of "run anywhere" instead of "run everywhere," which is essential for the test fixtures to be implemented as dependencies, as discussed in #1577.

Let me know about your thoughts.

**Comment by victorusu** [comment]
@vkarak, I supposed that the number of elements in the key can vary right? Something like
```python
        self.valid_environs = {
            ('daint', 'dom', 'pilatus'): ['PrgEnv-gnu', 'PrgEnv-intel'],
            ('arolla', 'tsa'): ['PrgEnv-gnu-nompi'],
            ('eiger'): ['PrgEnv-gnu']
        }
```

**Comment by jjotero** [comment]
I would just add the option to set `valid_prog_environs` as both a dict and a list. If it is a dict, then ReFrame would just do that `if self.current_system.name` under the hood and transform that into its current list format. No need to deprecate anything.

And even more importantly, I would definitely avoid adding another variable with either `environ`,  `env`, or anything related. There are a few of those in the code already and we must be specific on what an environment is on each of these variables.

**Comment by ekouts** [comment]
Could users repeat systems, like this?
```python
    valid_environs = {
        ('daint', 'dom', 'eiger'): ['PrgEnv-gnu', 'PrgEnv-intel', 'PrgEnv-pgi'],
        ('arolla', 'tsa'): ['PrgEnv-gnu-nompi'],
        ('eiger'): ['PrgEnv-aocc']
    }
```
The new syntax looks fine to me, but it can also lead to unnecessary repetition.

**Comment by vkarak** [comment]
@jjotero You are right, it's better to overload the syntax of `valid_prog_environs`.
@ekouts @victorusu Yes, but I'm not entirely convinced of having tuples as keys. Also you have a syntax error on on `eiger`. To become a tuple it must be `('eiger',)`.

**Comment by vkarak** [comment]
@ekouts You have a point there! Having tuples as keys complicates things, unnecessarily in my opinion.

**Comment by jjotero** [comment]
> The new syntax looks fine to me, but it can also lead to unnecessary repetition.

I see that repetition as a feature! 
```python
valid_prog_envs = set()
for k, v in self.valid_prog_environs.items():
    if self.current_system.name in k:
        valid_prog_envs.update(v)

self.valid_prog_environs = list(valid_prog_envs)
```
When parsing that dict, we loop over each entry and we build a set with all the `valid_prog_environs` from the union of all the entries. So in the example above, Eiger would get all 4 valid programming environments. Then this becomes entirely flexible and it would be just up to the user on how to define all these groups.

**Comment by teojgo** [comment]
Would it make sense to have also the partition included in the system?

**Comment by vkarak** [comment]
This is effectively achieved with the extended syntax of `valid_systems` and `valid_prog_environs` introduced in #2479, where you can select partitions and environments based on features and extras and since an environment may be define different features/extras per partition at the configuration level, we effectively implement the feature requested here. As a matter of fact, since #2479 ReFrame no more treats `valid_systems` and `valid_prog_environs` independently but it internally constructs a dictionary of partitions and their valid environments, in order to actually decide on skipping tests or assigning partition and environments to fixtures.
