### ISSUE TITLE
Investigate ways for assigning `sanity_patterns` at the class level

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1981]
You can now do this if you're not using `self.stdout` or `self.stderr`, but it would be nice to have a way to allow this also in the common cases that use stdout or stderr.

Replaces #1974.

**Comment by jjotero** [comment]
What I had in mind was something like the following:
```python
@rfm.simple_test
class MyTest(rfm.RunOnlyRegressionTest):
    valid_prog_evirons = ['*']
    valid_systems = ['*']
    executable = 'echo bananas'

    @sanity_function
    def set_sanity(self):
        return sn.assert_found(r'bananas', self.stdout)
```
Here, the `sanity_function` decorator (or whichever other name we go for) makes this function a deferred expression and registers it as the sanity function. The idea is that this decorator is only allowed once per class body, and derived classes may override this sanity function by either overriding `set_sanity` or decorating any other function with the `sanity_function` decorator. For example:
```python
@rfm.simple_test
class MyDerivedTest(MyTest):

    @sanity_function
    def new_sanity_function(self):
        '''This function is now the only sanity function.'''
        return sn.all([
            sn.assert_not_found(r'error', self.stderr),
            self.set_sanity()
        ])
```
This would make it very easy to compose and override sanity functions. We could also expose the `deferred` decorator to make functions deferred without marking them as the sanity function.

**Comment by jjotero** [comment]
Implementation of this one is done in https://github.com/jjotero/reframe/tree/feat/sanity
However, I'm holding the PR as this would just cause conflicts with other PRs that are currently open.
