### ISSUE TITLE
Specifying requirements, rather than e.g. valid_systems, for better test portability

### ISSUE THREAD

**Issue by casparvl** [eth-cscs/reframe#1987]
**The issue**

The problem I want to solve is that I want to write a test for GPUs, that is portable to other systems. By portable I mean: the end-user should only have to modify the ReFrame configuration file, but should not have to touch my test. 

**Current options**

Suppose we have a test that only runs on GPUs. Currently, I could define in my reframe config a partition with something like

```
{
  'name': 'gpu',
   ...
  'devices': [
    {
      'type': 'gpu',
      'num_devices': 2,
    },
  ],
},
```
and in my tests I could do something like 

```
valid_systems = ['my_system:gpu']
```

The issue I have with this is that this puts system specific information (namely: which systems are valid) in my ReFrame test. I feel that's bad practice in general: the test definition should contain as little system specific information as possible. This makes them more portable ánd more maintainable.

*Option 1*

Of course, I could tell everyone one who wants to use this test "you _have_ to specify a system named 'my_system' with a partition 'gpu'", but that's clearly an ugly solution: the ReFrame configuration file should desribe the system, it should not be defined by tests you want to run... (and: what if you have two GPU partitions? Only one can be named 'gpu' and would run this test...)

*Option 2*

@victorusu pointed me to this option.

I could have the ReFrame test check if the current partition has a gpu device, and if not, skip it:
```
@rfm.run_after('setup')
def skip_if_no_gpu(self):
  device_count = [ dev.num_devices for dev in self.current_partition.devices if dev.device_type == 'gpu' ]
  self.skip_if(device_count == 0)
```
This would work, but (as @victorusu  himself said) is quite ugly. It still creates the test as part of the DAG and then at runtime decides to skip it. Furthermore, I have to write logic in the test itself for this selection, which is less readable then 'only' specifying the requirements.

**Requested feature**

It would be great if a test could specify something like `partition_requirements` in the `__init__`, which are then matched to the partition's properties described in the ReFrame config file. The test should only be added to the execution graph for those partitions that meet the requirements. Note that this is actually very similar to how `valid_systems` works, but rather than specifying explicitely which partition is valid (which is system-specific), you specify a generic hardware requirement (which is test-specific, and thus has every 'right' to be in the test definition file). In fact, I think specifying the `partition_requirements` could completely replace the `valid_systems`, since before we would use `valid_systems` mostly because we _knew_ that a certain partition met certain requirements - and therefore included it in `valid_systems`.

Example test definition (using the same config file as above):
```
def __init__(self):
    self.partition_requirements = {
       'devices': {
         'type': 'gpu'
       }
    }
```
This test should then only be added to the DAG for those partitions that list a device with type 'gpu'.

Note that such a selection mechanism could be quite powerful: it could also be used to require a minimal number of GPUs or CPU cores, e.g.
```
def __init__(self):
    self.partition_requirements = {
       'processor': {
         'num_cpus': 24
       }
    }
```
Could mean this test needs at least need _at least_ 24 cores. This means we'd have to agree that if a requirement is a number, it's always a minimal requirement - but I think that makes sense in 99% of cases anyway.

Note that if I want to give this test to another end-user, I still need to impose _some_ limitation, since the device type is a free text item. I.e. I'd still need to tell him/her to list their GPU devices in the partitions as `'type': 'gpu'`. Nonetheless, it's a much more liberal requirement compared to imposing a specific system & partition name (as in option 1). It also extends more naturaly to multiple requirements (what if your test needs at least 1 gpu and 8 CPU cores? You wouldn't want to impose naming your partition gpu1_cpu8...).

**Comment by vkarak** [comment]
I thought about this this today and I think we can have a probably nice solution. Instead of introducing a new field, we can expand the syntax that the `valid_systems` and `valid_prog_environs`. An entry of these lists, apart from a system name or programming environment, will be also be able to be a _spec_ that specifies features or properties of a partition or environment. Each entry in those lists is practically OR'ed as it happens with the system/prog. env. names and a single entry might encode multiple features and/or properties, in which case these are AND'ed. Here is an example:

```python
# This will run on any prog. env with the `cuda` feature and defines the `mpi_abi` property to `mpich`.
valid_prog_environs = ['+cuda %mpi_abi=mpich']

# This will run on any prog. env that defines `compiler_family` as either `gnu` or `clang` and don't define the `mpi` feature
valid_prog_environs = ['%compiler_family=gnu -mpi', '%compiler_family=clang -mpi']
```

To implement this feature, we would need to add another field in the partition and environment configuration, named `features`, which will list a set of boolean features for the environment. The property look up will happen in the current `extras` dictionary.

I am claiming that the framework should not understand any specific features or properties and these should be entirely left to the test implementors. The feature and properties space is infinitely large and can be very specific to the domain of tests or the purpose of the systems. It should be up to a test library to document the feature of systems/prog. envs that it recognises so that it allows for the proper configuration of the framework. Apparently, for `hpctestlib` we will come up with a set of features and properties to expect in the system/prog. env. definitions, but we expect this list to evolve and be refined in the future.

**Comment by casparvl** [comment]
Yeah, that sounds like a promising approach. The only downside would be a small amount of duplication in the settings file: I would e.g. need to specify

```
'features' = ['gpu'].
'devices': [
{
    'type': 'gpu',
    'num_devices': 2,
}
```

Since I would still need want to define (and extract) the number of devices per node from in the settings file. But, that's a small price to pay and not a huge issue in my view.

> I am claiming that the framework should not understand any specific features or properties and these should be entirely left to the test implementors. The feature and properties space is infinitely large and can be very specific to the domain of tests or the purpose of the systems. 

I am not sure I agree with this, but that's personal preference I guess. Yes, the feature and properties space _is_ infinitely large. But there is also a large set that would be common for a lot of users and it would be nice if the framework would standardize this, rather than each individual testlib having to choose something. Standardizing _some_ feature names does not mean we have to disallow custom feature names for more exotic things. I can imagine `gpu`, `cuda`, `hip` would be a standard features, while something like `tensorfloat32` (for a test that specifically tests the `tensorfloat32` datatype) would be custom. If we don't standardize the first three, we get test libraries where some of them call it `cuda`, some `CUDA` and some maybe `nvidia`. If I would use tests from several test libraries, I might need a settings file that defines all of them... Features could imho be standardized in an enumerator that simply enumerates standard strings. That would make it possible to easily mix and match standard and custom features:

```
features = [reframe.features.cuda, 'my_custom_feature']
```

**Comment by casparvl** [comment]
Hm, I thought about this a bit more, and one case that wouldn't be clear to me: what if you want to specify you need a certain amount of memory? How would we do that with the features you described? Sure, I could create a feature `mem_large` and define that this means it needs at least 256 GB or something, but it's awkward to create a boolean when your requirement is on an int or float.

Also, I'm actually already defining a memory requirement in some way if I follow this example: https://reframe-hpc.readthedocs.io/en/stable/tutorial_advanced.html?highlight=memory#adding-job-scheduler-options-per-test

```
# Settings.py:
'resources': [
    {
        'name': 'memory',
        'options': ['--mem={size}']
    }
],
...
# test.py:
@run_before('run')
    def set_memory_limit(self):
        self.job.options = ['--mem=1000']
```
It would be nice if I wouldn't then _also_ need to define a feature, and a feature requirement separately. What bites us here is actually that something like resources _is_ generic. If it would have been standardized, and e.g. the use would only have to define in the config how to request memory on their system (similar to how `access` works):
```
#Settings.py
# some_partition:
'max_mem': 2000
'mem_flag': '--mem'

# some_other_partition:
'max_mem': 500
'mem_flag': '--mem'
```
And then there would be a standard value that could be set in the class body
```
#test.py
memory = 1000
```
There would be no need for a specifying a separate requirement: the framework would just figure out this test can be run on `some_partition` by passing `--mem=2000` to the scheduler, but it won't fit on `some_other_partition`.

I have the feeling you are reluctant to introduce specific fields in order to keep full flexibility, but I also feel that the price we pay for that is the duplication of information in the test/settings file, since the framework can't know that these generic items (an extra_resource that refers to memory, and a feature that refers to memory) actually refer to the same concept.

**Comment by vkarak** [comment]
Another idea for adding metadata to the environment configuration is to add a `family` property that would take values such as `gcc`, `cce` etc. and then internally we expand the programming environment API with properties such those in Spack's [compiler backends](https://github.com/spack/spack/blob/develop/lib/spack/spack/compilers/cce.py), so that a test can do `self.current_environ.openmp_flag` and get the OpenMP flags in a environment-agnostic way. We could also allow users in their environment definitions to set those properties.
