### ISSUE TITLE
Set `skipkeys=True` as default arg in `json.dump`

### ISSUE THREAD

**Issue by jjotero** [eth-cscs/reframe#2022]
At the moment it defaults to `False` and it causes problems when creating a dict with tuples as keys.

**Comment by victorusu** [comment]
We need to investigate whether this change impacts the report file generated at the end of reframe's run.
I wonder if could convert non-string things to strings using [`utility.toalphanum`](https://reframe-hpc.readthedocs.io/en/stable/_modules/reframe/utility.html?highlight=toalphanum#).

An example of a workflow that the`skipkeys=False` hinders
```
REFERENCE_GPU_PERFORMANCE = {
    (daint:gpu, dom:gpu) : {
        'A': (30.0, -0.05, None, 'ns/day'),
        'B': (30.0, -0.05, None, 'ns/day'),
    }
}

class MyBaseTest(rfm.RunOnlyRegressionTest):
    test_perf_reference = variable(dict)
    benchmark = ['A', 'B']

    @run_before('sanity'):
    def set_pref_reference(self):
        cp = self.current_partition.fullname:
        for k, v in self.test_perf_reference.items():
            if cp == k:
                self.reference[cp] = {self.benchmark: k}
                
class MyGPUTest(MyBaseTest):
    test_perf_reference = REFERENCE_GPU_PERFORMANCE
```

PS: I hope that this Python works, I haven't tested it... :-)

**Comment by victorusu** [comment]
@vkarak, what do you think about it?

**Comment by jjotero** [comment]
Also useful for #1852
