### ISSUE TITLE
Add more unit tests to the scoped dictionary

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#206]
We need to add a couple of unit tests more to the scoped dictionary that would test the (correct) behaviour described in #60. More specifically:

1. Adding a scope with a same name as a key:
```python
scoped['s0:s1'] = 1
scoped['s0:s1:k0'] = 2
assert scoped['s0:s1'] == 1
assert scoped['s0:s1:k0'] == 2
del scoped['s0:s1']
assert scoped['s0:s1:k0'] == 2
scoped['s0:s1']   # -> this should raise `KeyError`
```

2. Nested scopes are not deleted even if the parent scope is deleted.

**Comment by teojgo** [comment]
In the example above, when we do `del scoped['s0:s1']` scope `s0:s1` is deleted so that the assertion after the deletion fails. I am printing the scoped dict before and after deletion:
```
scoped = ScopedDict()
scoped['s0:s1'] = 1
scoped['s0:s1:k0'] = 2
print(scoped)
>> {'s0': {'s1': 1}, 's0:s1': {'k0': 2}}
del scoped['s0:s1']
print(scoped)
{'s0': {'s1': 1}, 's0:s1': {'k0': 2}}
```

**Comment by vkarak** [comment]
The correct behaviour is described in my comment at the beginning. Any scoped-dict key must be treated as `<scopes>:<key>`. So the `s0:s1` should be translated to `s1` key of the `s0` scope. If no such key exists, then the scope `s0:s1` must be deleted. I think the corresponding check in `__delitem__` must be inversed.

**Comment by teojgo** [comment]
The deletion treads `s0:s1` as a key and does not treat it as `s1` item of `s0`. Therefore, the implementation of the deletion has to be changed.

**Comment by vkarak** [comment]
That's exactly my point. The implementation of `__delitem__` is buggy and should be fixed. Because, currently, there is no way to delete a key that has the same name as a scope.
