### ISSUE TITLE
Run all hooks in the test's stage directory

### ISSUE THREAD

**Issue by jjotero** [eth-cscs/reframe#2067]
When entering a hook, the pipeline should cd into the test's stage directory.

**Comment by victorusu** [comment]
I think it doesn't make sense for all hooks to enter the stage dir. Only those that happen after the setup, because that's when the stage dir is created... 
I think we should not forget to explicit say this on the documentation.

**Comment by jjotero** [comment]
Yeah, good catch.

**Comment by jjotero** [comment]
Decided to update the docs instead of doing the automatic `cd`
