### ISSUE TITLE
ReFrame crashes when trying to autodetect topology and does not have write permissions in `config/_meta`

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#2072]
This is triggered when ReFrame is installed with e.g EasyBuild system-wide, since at the first execution ReFrame tries to create `config/_meta` if this is not already there.

**Comment by vkarak** [comment]
I suggest always user's `$HOME` to store the metadata then. It's the safest way. This issue is quite important, because it can render unusable system-wide deployments of ReFrame.
