### ISSUE TITLE
Automatic handling of `SPACK_ROOT`?

### ISSUE THREAD

**Issue by giordano** [eth-cscs/reframe#2097]
The Spack build system implicitly requires the `SPACK_ROOT` environment variable to be defined, but this requirement isn't written down explicitly, besides the fact the variable is now mentioned in the new [Spack tutorial](https://reframe-hpc.readthedocs.io/en/v3.7.1/tutorial_build_automation.html#using-spack-to-build-the-test-code).

The problem I'm facing is that `SPACK_ROOT` may be defined in the login node but not in the compute node.  The workaround I'm using is to have in the tests
```py
    variables = {
        # ...
        'SPACK_ROOT': os.getenv('SPACK_ROOT'),
    }
```
I guess I may not the be only one in this situation.  Should there be a more automatic handling of `SPACK_ROOT` (maybe automatise what I'm manually doing in the tests)?

**Comment by vkarak** [comment]
Hi @giordano, what if you set `SPACK_ROOT` in your partition config?

```python
variables: [['SPACK_ROOT', os.getenv('SPACK_ROOT')]]
```

Check [here](https://reframe-hpc.readthedocs.io/en/stable/config_reference.html#systems-.partitions-.variables).

**Comment by giordano** [comment]
Yes, that works, but it only moves the setting from the specific test to the system configuration.  I'm wondering whether I am the only one in a similar situation :thinking:

**Comment by vkarak** [comment]
I don't think that the the `Spack` build system should set the `SPACK_ROOT` in the test's `variables`. It's a user configuration matter if it is defined on the login nodes but not on the compute nodes, in which case a solution like the one I proposed is the most appropriate I think. On the other hand, I agree that we should mention that in the documentation explicitly.

**Comment by tgamblin** [comment]
`SPACK_ROOT` isn’t required. It’s not used anywhere in the code; the `spack` script finds itself and sets up `sys.path` from that.

You can use `SPACK_ROOT` to override the  prefix discovered by `share/spack/setup-env.(sh|csh|fish)`, but other than that it has no function. Sourcing those scripts will also find the spack prefix automatically and add `spack` to your `PATH` (even in csh and dash), but you can just add it yourself if you do not need Spack’s shell integration (for things like `spack load`, `spack env activate`, etc.)

Do you see `SPACK_ROOT` being required somewhere? It used to be required for the csh and dash setup scripts, but we used some black magic to get rid of that requirement.

**Comment by giordano** [comment]
It's ReFrame that explicitly uses this environment variable in the scripts it generates, see the [tutorials](https://reframe-hpc.readthedocs.io/en/v3.7.2/tutorial_build_automation.html#using-spack-to-build-the-test-code):
```sh
. $SPACK_ROOT/share/spack/setup-env.sh
```
If the variable is not defined the file `/share/spack/setup-env.sh` is sourced.

**Comment by tgamblin** [comment]
We have this problem in the spack tutorial too. We made the instructions agnostic to it: 

https://spack-tutorial.readthedocs.io/en/latest/tutorial_basics.html#installing-spack

basically we tell the user to clone spack, cd into the cloned repo, and source the script with a relative path. Then `$SPACK_ROOT` is defined.

Not sure if that helps but you could steal it if it does.

**Comment by vkarak** [comment]
Thanks @tgamblin for chiming in! @giordano Since we assume that `spack` is already available, I think that we could just find the prefix ourselves from the `spack` script and source it without using `$SPACK_ROOT` at all.

**Comment by tgamblin** [comment]
If you assume `spack` will be in `PATH` just run `spack location --spack-root`.

**Comment by vkarak** [comment]
> If you assume spack will be in PATH just run spack location --spack-root.

Yes, we do. So that's perfect!

**Comment by giordano** [comment]
For reference, my problem was that the ReFrame job scripts had
```sh
#!/bin/bash
```
as shebang, so my init file (which sets `SPACK_ROOT` and puts Spack in the `PATH`) wasn't loaded.  The solution was to use the [`RFM_USE_LOGIN_SHELL`](https://reframe-hpc.readthedocs.io/en/stable/manpage.html#envvar-RFM_USE_LOGIN_SHELL) environment variable.  With this, `SPACK_ROOT` is now set, and `spack` is in the `PATH`.

With #2123 there is no need to have `SPACK_ROOT` set, only `spack` being in the `PATH`.  `RFM_USE_LOGIN_SHELL` may still be needed be the end users, though.

BTW, from the docstring it isn't very clear what values are accepted by `RFM_USE_LOGIN_SHELL`: does it only need to be set?  I used `True`, but maybe anything, including `nope`, would work?
