### ISSUE TITLE
Cannot make `executable` required.

### ISSUE THREAD

**Issue by jjotero** [eth-cscs/reframe#2106]
If the `excutable` variable is `required` it will always be initialised by ReFrame in the pipeline's `__rfm_init__` method to the test's name. Whereas that is absolutely fine for either `RegressionTest` or `CompileOnlyRegressionTest`, this behaviour should not occur with `RunOnlyRegressionTest` classes, where the user should have the full power on requiring the `executable` variable.

Possible workaround: move this default assignment into the `compile` stage.

**Comment by vkarak** [comment]
> Possible workaround: move this default assignment into the compile stage.

I think that't the best thing and along the general idea that we set the variables as close as possible to their use. In tests that need to compile the code with `SingleSource`, this is the compile phase, otherwise it's the run phase.
