### ISSUE TITLE
Auto detection of remote partition topology fails with launcher not found error

### ISSUE THREAD

**Issue by mahendrapaipuri** [eth-cscs/reframe#2115]
When I try to auto-detect the processor topology of the remote partition, ReFrame fails to create JSON file. After looking into the verbose output, the job script it emits to detect the topology is as follows:

```
#!/bin/bash
#SBATCH --job-name="rfm-detect-job"
#SBATCH --ntasks=1
#SBATCH --output=rfm-detect-job.out
#SBATCH --error=rfm-detect-job.err
#SBATCH --partition=compute
#SBATCH --exclude=openhpc-compute-[8-15]

_onerror()
{
  exitcode=$?
  echo "-reframe: command \`$BASH_COMMAND' failed (exit code: $exitcode)"
  exit $exitcode
}

trap _onerror ERR

./bootstrap.sh
mpirun -np 1 ./bin/reframe --detect-host-topology=topo.json
```

Looks like ReFrame is not loading the modules defined in the system partition before calling `mpirun` to detect the topology. So, the job fails with error `line 19: mpirun: command not found`.  The problem will persist even if ReFrame loads the modules in the system partition and MPI is not there in the modules of system partition.

 A better solution could be to remove launcher from this job?

**Comment by ekouts** [comment]
Hi @mahendrapaipuri , thanks for reporting the issue.
> A better solution could be to remove launcher from this job?

Reframe needs to run in the nodes of the partition to get the right information and you need the launcher for this. Loading the module before running the first time Reframe would be a workaround for you, right? Reframe will not try to generate the topology files every time. I also opened a PR for this issue (#2140) but this needs a bit more thinking before merging.

**Comment by mahendrapaipuri** [comment]
Hello @ekouts, Well, I did not put my suggestion properly. What I mean is to use `local` launcher for this job. This way there are no dependencies on the modules the system loads, especially, dont have to depend on availability of `mpirun`. Adding 
`job.launcher = getlauncher('local')()` before this [line](https://github.com/eth-cscs/reframe/blob/152d697d59250f30664e7c7502ebf3680fd8af37/reframe/frontend/autodetect.py#L115) should avoid emitting `mpirun -np 1`, right? Excuse me if I completely missing something here. I had a very quick look at source code for detecting topology.

**Comment by ekouts** [comment]
Sorry, I misunderstood. I am very familiar with all the launchers that ReFrame supports 😅 In this case it wouldn't matter to use the local launcher like you said but with others it might be a problem. For example was using the `ssh` launcher, right? And I am not completely sure about the other launchers too.

**Comment by mahendrapaipuri** [comment]
Ok, I see what I am missing. I was being stupid. Of course, we need a launcher other than `local` to actually execute the command on the compute node. Without `mpirun -np 1`, batch schedulers will run the command on the login nodes and that is not correct behaviour. I think your PR should fix the issue. Sorry for misunderstandings!! Thank you!!
