### ISSUE TITLE
Mix of serial and parallel tests

### ISSUE THREAD

**Issue by yellowhat** [eth-cscs/reframe#2116]
Hi,
I would like to run some test in parallel meanwhile other in serial.
The real use is to run compute tests in parallel with storage benchmark of shared target (you do not want to run multiple differrent IOR at the same time on the same target).

Consider the following example:
```python
@rfm.simple_test
class ARunTest(rfm.RunOnlyRegressionTest):
    descr = "A Run"
    valid_systems = ["hpc:hpc"]
    valid_prog_environs = ["*"]
    param = parameter(["AA", "AB"])
#    max_jobs = 1

    def __init__(self):
        self.executable = f"date; echo {self.param}"

#    @run_before("run")
#    def set_exec(self):
#        self.current_partition.max_jobs = 1

    @sanity_function
    def assert_passed(self):
        return True

@rfm.simple_test
class BRunTest(rfm.RunOnlyRegressionTest):
    descr = "B Run"
    valid_systems = ["hpc:hpc"]
    valid_prog_environs = ["*"]
    param = parameter(["BA", "BB"])

    def __init__(self):
        self.executable = f"date; echo {self.param}"

    @sanity_function
    def assert_passed(self):
        return True
```

The `ARunTest` should run in serial: `ARunTest_AA` first and on completion start `ARunTest_AB`.
While `BRunTest` should run in parallel: `BRunTest_BA` concurrent to `ARunTest_BB`.

Using the default settings `ARunTest_AA`, `ARunTest_AB`, `BRunTest_BA`, `BRunTest_BB` run in parallel.
Instead using the option `--exec-policy=serial` it will run `ARunTest_AA` then `ARunTest_AB` then `BRunTest_BA` then `BRunTest_BB`.

The trick would be to set a `max_jobs = 1` variable for the class `ARunTest` but it is simply skipped.
Or:
```python
    @run_before("run")
    def set_exec(self):
        self.current_partition.max_jobs = 1
```
but I get: `can't set attribute self.current_partition.max_jobs = 1`

It there a workaround for this?

Thanks

**Comment by jjotero** [comment]
Hi @yellowhat ! I think you can serialise the execution of some tests by making them dependent on each other. Would this do the trick?

**Comment by yellowhat** [comment]
Yes that should work. But how do I make `ARunTest` depend on itself?

**Comment by jjotero** [comment]
You don't need that. if `ARunTest` is the one that is meant to run first, ReFrame will see that it is the only one without a dependency and then run first. All the others depending on `ARunTest` will simply have to wait until `ARunTest` is done, because they `depend_on` it.

**Comment by yellowhat** [comment]
So are you suggesting:
```python
@rfm.simple_test
class ARunTest(rfm.RunOnlyRegressionTest):
    descr = "A Run"
    valid_systems = ["hpc:hpc"]
    valid_prog_environs = ["*"]
    param = parameter(["AA", "AB"])

    def __init__(self):
        self.executable = f"date; echo {self.param}"

    @run_after("init")
    def set_depends_on(self):
        self.depends_on("ARunTest", udeps.fully)

    @sanity_function
    def assert_passed(self):
        return True
```

**Comment by jjotero** [comment]
No. A test cannot depend on itself. What I say is that the test that is meant to run first does not have a dependency. The second test to run depends on the first one. The third test to run depends on the second one. And so on.

**Comment by yellowhat** [comment]
So you are suggestin to create `n` classes of `ARunTest`? Seems a bit overkill.

**Comment by jjotero** [comment]
Nope. If your test `A` is parameterised with `parameter(["AA", "AB"])`, you can make test `A_AB` depend on test `A_AA`. The test `A_AA` should have no dependencies, because that's the one you want to make run first. You can access a test's namespace with `self._rfm_param_space` if you want to automate this in some way.

There are a few open issues to address this rather complex way of "serialising" the test execution, and we're on it. But for now, I'm afraid this is the available workaround :)

**Comment by yellowhat** [comment]
Ok, I will have a look at `self._rfm_param_space` and report my finding,
Is there a pull request I can follow for this topic?

Thanks

**Comment by jjotero** [comment]
There are a few issues and PRs. This issue is far more complex than it might seem at first glance and it hits the framework a bit everywhere. Addressing this properly will force us to introduce some disruptive changes, so I'd say that most of the PRs that you'll see will be somewhat related to this.

The parameter space is just a fancy namespace, so `self._rfm_param_space['param']` should give you a tuple with `("AA", "AB")`.

**Comment by yellowhat** [comment]
Thanks for the information.
I will have a play and report back.

**Comment by yellowhat** [comment]
I have tried the following:
```python
@rfm.simple_test
class ARunTest(rfm.RunOnlyRegressionTest):
    descr = "A Run"
    valid_systems = ["hpc:hpc"]
    valid_prog_environs = ["*"]
    param = parameter([["A00", "A01"], ["A10", "A11"]])

    def __init__(self):
        self.executable = f"date; echo {self.param[0]} {self.param[1]}"

    @run_after("init")
    def set_depends_on(self):
        for param in self._rfm_param_space["param"]:
            dep = "".join(f"__{p}__" for p in param)
            dep = f"ARunTest_{dep}"
            self.depends_on(dep, udeps.fully)

    @sanity_function
    def assert_passed(self):
        return True
```

But I have no idea how to solve the dependency loop:
```
./reframe/bin/reframe: run session stopped: dependency error: found cyclic dependency between tests: ARunTest___A10____A11__->ARunTest___A10____A11__
```

**Comment by jjotero** [comment]
Yup, that's because you're making all tests depend on all the parameter variants (including its own variant). You don't need all test to depend on each other. You just need to create a sequence. Look at the modified version of your post-init hook below:
```python
    @run_after("init")
    def set_depends_on(self):
        for i, param in enumerate(self._rfm_param_space["param"]):
            if param == self.param:
                if i != 0:
                    dep = "".join(f"__{p}__" for p in prev_param)
                    dep = f"ARunTest_{dep}"
                    self.depends_on(dep, udeps.fully)
                break
            elif param != self.param:
                prev_param = param
```

-  If `param == self.param` and `i == 0`, that means that this is the first node in the execution graph. So we just break. The first node must not have any dependencies.
- If `param == self.param` and `i != 0`, then we need to make this test dependent on the previous test. We just need 1 dependency per tests, so we break right after.
- If `param != self.param`, just keep track of the previous parameter value and continue.

This would of course get far more complicated if you had 2 parameters or more in the test, but that's exactly why we're working on a way to make this easier 🙂

**Comment by yellowhat** [comment]
A minimal example:

```python
@rfm.simple_test
class ARunTest(rfm.RunOnlyRegressionTest):
    descr = "A Run"
    valid_systems = ["hpc:hpc"]
    valid_prog_environs = ["*"]
    param = parameter([["A00", "A01"], ["A10", "A11"], ["A20", "A21"]])

    def __init__(self):
        self.executable = f"date; echo {self.param[0]} {self.param[1]}"

    @run_after("init")
    def set_depends_on(self):
        lst = self._rfm_param_space["param"]
        idx = lst.index(self.param)
        for param in lst[:idx]:
            dep = "".join(f"__{p}__" for p in param)
            dep = f"ARunTest_{dep}"
            self.depends_on(dep, udeps.fully)

    @sanity_function
    def assert_passed(self):
        return True
```

```console
[----------] started processing ARunTest___A00____A01__ (A Run)
[ RUN      ] ARunTest___A00____A01__ on hpc:hpc using gcc
[----------] finished processing ARunTest___A00____A01__ (A Run)

[----------] started processing ARunTest___A10____A11__ (A Run)
[ RUN      ] ARunTest___A10____A11__ on hpc:hpc using gcc
[      DEP ] ARunTest___A10____A11__ on hpc:hpc using gcc
[----------] finished processing ARunTest___A10____A11__ (A Run)

[----------] started processing ARunTest___A20____A21__ (A Run)
[ RUN      ] ARunTest___A20____A21__ on hpc:hpc using gcc
[      DEP ] ARunTest___A20____A21__ on hpc:hpc using gcc
[----------] finished processing ARunTest___A20____A21__ (A Run)
```

Should this example code be part of *Tutorial 4: Tips and Tricks* (https://reframe-hpc.readthedocs.io/en/stable/tutorial_tips_tricks.html)?

**Comment by jjotero** [comment]
Hi @yellowhat ! Glad that it worked. We will probably add the corresponding tutorial once we address all the issues mentioned above. This case access protected variables (`_rfm_param_space`) and it would get a lot more complicated if one has 2 or more parameters, so this is by all means a workaround and I doubt is general enough for the general audience.
