### ISSUE TITLE
List available programming environments defined for a system

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#215]
it would be nice to have a frontend flag that would list all the available programming environments for a given system. Something like:

```bash
reframe --list-prgenvs
output:
system XXXXX 
List of prgenvs:
PrgEnv-gnu
   CXX: mpic++
   CC: mpicc
   FTN: mpif90
...
```

And it would be nice to combine with the system flags, so one could probe the configured environments for other machines other than the one he has. Of course, provided that he has the correct configured environment for the other machines.
```
reframe --list-prgenvs --system daint
output:
system daint 
List of prgenvs:
PrgEnv-gnu
   CXX: CC
   CC: cc
   FTN: ftn
...
```

**Comment by vkarak** [comment]
This is related to #306.
