### ISSUE TITLE
The order of execution of inherited hooks is currently undocumented and probably wrong

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#2268]
In the following example, we do not document in which order the hooks of the `setup` stage will execute:

```python
class TestA(rfm.RunOnlyRegressionTest):
    @run_after('setup')
    def x(self):
        print('x')

class TestB(TestA):
    @run_after('setup')
    def y(self):
        print('y')
```

The order of execution is `TestB.y`, `TestA.x`, but this is not documented. This is quite important to be documented, because it affects test library design. Also I think that the order of execution is wrong, from a test library's perspective. If `TestA` is a library and sets some variable in a stage hook, I want to be able to use the value of that variable in my derived test.

**Comment by mahendrapaipuri** [comment]
Agree about changing the execution. When I started writing tests, I assumed that `TestA` would be executed first and then `TestB` only to figure out later that is not the case. I forgot to raise this issue and I adapted my tests with the current execution order. 

Yes, I think there is a need to change this order and also documentation will be really helpful!

**Comment by vkarak** [comment]
Thanks @mahendrapaipuri, #2273 should solve this issue.
