### ISSUE TITLE
cannot disable exclusive_access from cmd line

### ISSUE THREAD

**Issue by smoors** [eth-cscs/reframe#2303]
I have a test that sets variable `exclusive_access` to True:
```
@rfm.simple_test
class BLASTest(rfm.RunOnlyRegressionTest):
    exclusive_access = True
    ...
```
According to the docs:
>Variable assignments passed from the command line happen before the test is instantiated and is the exact equivalent of assigning a new value to the variable at the end of the test class body. 

However, trying to override this from the cmd line does not work for me, ReFrame still adds the Slurm `--exclusive` flag:
```
reframe --verbose --run --checkpath blas.py --system hydra:skylake --prgenv foss-2020a --setvar BLASTest.exclusive_access=False --setvar num_cpus_per_task=4
```
I've tried setting it to `0`, `False`, `@none`, but nothing seems to work.
Am I doing something wrong? What's the right way to set this to False?
In any case, it does *not* show a warning that the variable is not set, so it's doing something with it.

**Comment by teojgo** [comment]
Actually, are you setting in any subsequent hook?

**Comment by smoors** [comment]
I tried with `exclusive`, but that gives the following warning:
```
/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/bin/reframe: test 'BLASTest': the following variables were not set: 'exclusive'
```

**Comment by smoors** [comment]
> Actually, are you setting in any subsequent hook?

no

**Comment by teojgo** [comment]
Yeah, the `exclusive` was my mistake.

**Comment by vkarak** [comment]
I could reproduce this and it seems like a bug.

**Comment by smoors** [comment]
thanks for looking into this.

as a workaround, I found that using `--setvar exclusive_access=` (i.e. not assigning any value to it) does work.

**Comment by teojgo** [comment]
@smoors yes, in this case the empty string will be interpreted as `False`. But it's better to have some dedicated special values like `@true` and `@false` to set booleans explicitly. What do you think?

**Comment by smoors** [comment]
@teojgo I agree that it's better to be able to set it explicitly.

for me, the least surprising way to implement this would be to interpret any of 'False', 'false', 'no', '0' as `False`.
`@true` and `@false` would work too if it's well documented, and if ReFrame gives a clear error if any other values are given.

**Comment by vkarak** [comment]
> for me, the least surprising way to implement this would be to interpret any of 'False', 'false', 'no', '0' as False.
@true and @false would work too if it's well documented, and if ReFrame gives a clear error if any other values are given.

#2309 fixes the problem and adds a warning in the documentation. However reframe does not issue an error if any other values are given.
