### ISSUE TITLE
ReFrame ignores num_cpus_per_task for CompileOnlyRegressionTest

### ISSUE THREAD

**Issue by smoors** [eth-cscs/reframe#2304]
I tried setting `num_cpus_per_task = 4` in the class body of a `CompileOnlyRegressionTest`, but ReFrame ignores it.
I also tried setting it with:
```
    @run_after('setup')
    def set_cpus_per_task(self):
        self.job.num_cpus_per_task = 4
``` 
but apparently there is no `job` object defined for `CompileOnlyRegressionTest`, as I get this error:
```
AttributeError: 'NoneType' object has no attribute 'num_cpus_per_task'
```

**Comment by mahendrapaipuri** [comment]
I think ReFrame will take `num_cpus_per_task` into account only when we set `build_locally=False`, ie., when we want to build on the remote node. What exactly are you trying here by using `num_cpus_per_task` for compiling the sources? Maybe you are looking for `build_system.concurrency`?

**Comment by smoors** [comment]
@mahendrapaipuri thanks for the reply.

I should have mentioned that I have indeed set `build_locally=False` to run the build step on the remote node. I've added `num_cpus_per_task` in order to speed up the build, but that does not work for some reason: only one core is requested/allocated for the job.

**Comment by smoors** [comment]
`self.num_cpus_per_task` did not work, but `self.build_job.num_cpus_per_task` does work (that's probably what you meant?)

as a suggestion, maybe you could automatically set `self.build_job.num_cpus_per_task` equal to `self.num_cpus_per_task` if not defined?

anyway, thanks a lot for the help!

**Comment by vkarak** [comment]
I am not sure that is a good idea to always use the `RegressionTest.num_cpus_per_task` for the build job. It probably makes sense for compile-only test, but not sure if it does for any `RegressionTest`. On the other hand, the various attributes of the `Job` class are not documented, while they could, especially now that we have two types of jobs, build jobs and run jobs. I'm keeping this open, until we conclude on a request for enhancement either for the framework or simply for the documentation.

**Comment by mahendrapaipuri** [comment]
@vkarak The way I understood is `RegressionTest.num_*` attributes are inherited by ONLY "run" job and not `build_job`. I think that is why even in the case of  `CompileOnlyRegressionTest`, setting `self.num_*` did not have any effect on `build_job` (from what @smoors told us). Am I seeing it correctly?

**Comment by vkarak** [comment]
@mahendrapaipuri Yes, this is right. I generally believe that we should simply expose the `Job` attributes so that users can adapt the `build_job`. After all, this is not the most common operation.

**Comment by vkarak** [comment]
Opened #2315.
