### ISSUE TITLE
`install_opts` 'target' is not correctly included in spack build script

### ISSUE THREAD

**Issue by rhenwood-arm** [eth-cscs/reframe#2331]
Using this code to generate multiple builds with spack:

```class build_x_text(rfm.RegressionTest0):
	target_arch = parameter(['aarch64', 'haswell', 'skylake'])
	build_system = 'Spack'
	
	@run_before('build')
	def prepare_build(self):
		self.build_system.install_opts = [f'target={self.target_arch}']
```

results in a spack script that looks like this (for an example of bzip2):
```
...
spack env create -d rfm_spack_env
spack env activate -V -d rfm_spack_env
spack config add "config:install_tree:root:opt/spack"
spack add bzip2@1.0.8
spack install target=aarch64
```

This gives an error in spack: `==> Error: Spec has no name; cannot concretize an anonymous spec`

If the script is manually adjusted to move `target=aarch64` to the the `spack add ...` line, spack correctly builds bzip2.

**Comment by rhenwood-arm** [comment]
FYI: I have a work-around:
```
target_arch = parameter(['aarch64', 'haswell', 'skylake'])
SPACK_SPEC = "bzip2@1.0.8"

@run_before('compile')
def specify_build    
    self.build_system.specs = [f'{SPACK_SPEC} target={self.target_arch}']
```

**Comment by rhenwood-arm** [comment]
It also appears that `self.build_system.cflags` (as documented here: https://reframe-hpc.readthedocs.io/en/stable/regression_test_api.html?highlight=cflags#reframe.core.buildsystems.BuildSystem ) is not honored when using spack as the build system.

**Comment by rsarm** [comment]
@rhenwood-arm I would write that as you are doing in your workaround. For instance
```python
self.build_system.specs = ['bzip2@1.0.6 target=aarch64',
                           'bzip2@1.0.6 target=haswell']
```
since `target` is part of the spec. That creates the `spack.yaml` file
```yaml
spack:
  specs: [bzip2@1.0.6 arch=darwin-None-aarch64, bzip2@1.0.6 arch=darwin-None-haswell]
  view: true
  config:
    install_tree:
      root: opt/spack
```
`build_system.install_opts` are options to be passed to the `spack install` command.
What do you think?

**Comment by vkarak** [comment]
> It also appears that self.build_system.cflags (as documented here: https://reframe-hpc.readthedocs.io/en/stable/regression_test_api.html?highlight=cflags#reframe.core.buildsystems.BuildSystem ) is not honored when using spack as the build system.

Yes, this is true, and it should be a separate issue.

Also, I agree with @rsarm that `install_opts` behaves correctly as it adds options to the `spack install` command. What you probably request here is to add the `target` to the generated environment so that you don't have to specify it in each spec.
