### ISSUE TITLE
Partition's `time_limit` does not define a default value in the config schema

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#2388]
```
./bin/reframe --show-config=systems/0/partitions/@default/time_limit
```

```
./bin/reframe: no such configuration parameter found: systems/0/partitions/@default/time_limit
```

**Comment by mahendrapaipuri** [comment]
Is a default value for `time_limit` needed? If the user do not set a `time_limit`, the emitted job script will not have a `walltime` in directive which then simply fallback to default limits set on the system scheduler. Is it not the intended behavior?

**Comment by vkarak** [comment]
Yes, for consistency. We should have it as `null` and if so, then no time limit option is passed.

**Comment by teojgo** [comment]
@vkarak This happens also for `general/junit_report` since the `null` valud in the schema is not recognized.

**Comment by vkarak** [comment]
@teojgo We should add this, too, then.

**Comment by teojgo** [comment]
@vkarak the problem lies into how we handle `None` when we get the site configuration option. the default value for `report_junit` is already in the schema
