### ISSUE TITLE
Add Support for "Standard" Spectrum LSF Scheduler

### ISSUE THREAD

**Issue by nicolas-tallet** [eth-cscs/reframe#2389]
The following issue was about introducing support for Spectrum LSF as a scheduler into ReFrame:

https://github.com/eth-cscs/reframe/issues/1055

but it was actually focused on a Spectrum LSF variant which is rather specific to LLNL Sierra system, where LSF is used together with IBM Cluster System Management (CSM).

On regular HPC platforms, Spectrum LSF is not used in conjunction with CSM, which makes the current implementation inadequate as the submission command / several options are different.

Would it be possible to add support for "standard" Spectrum LSF into ReFrame?

**Comment by vkarak** [comment]
Hi @nicolas-tallet, there is the PR #2383 that enhances LSF support. Could you test that?

**Comment by nicolas-tallet** [comment]
Hi @vkarak , sure, will have a look a it. Thanks.
