### ISSUE TITLE
Allow different ways of specifying a hostname command through the configuration 

### ISSUE THREAD

**Issue by rsarm** [eth-cscs/reframe#2440]
On #2216 the hostname detection was changed from `socket.gethostname()` to `socket.getfqdn()`. For some systems that's not convenient. We discussed internally the possibility of giving the option of specifying one of them through the configuration.

**Comment by vkarak** [comment]
Hi @rsarm can you elaborate on this use case?

**Comment by ireed** [comment]
Cloud is a specific use case where this would be helpful. 
As you correctly pointed out in [#2444](https://github.com/reframe-hpc/reframe/pull/2444#pullrequestreview-893894274), cloud configurations do not know the hostname until provisioning is complete. This requires a reframe [hack](https://github.com/JonShelley/reframe/blob/52e4ff0473703ab0b6f7f6002b6b003bf5df6050/reframe/core/config.py#L279-L298) for using an alternate method to get hostnames, as you also pointed out. 

But, notice that this requires us to maintain a separate forked repo specifically for that feature, which doesnt allow us to pull the latest reframe when doing our automated tests. Any suggestions? 

One solution would be to have an empty function in the config.py that users can fill in a separate, stand-alone python file. This way, we can pull the main/real reframe code, then pull our additional file.

**Comment by vkarak** [comment]
@ireed I agree that we need to make the configuration auto-detection more cloud friendly. I suggest opening a new issue for that so that it gets the proper attention and gets prioritised. We can resume the discussion on what's the best way to implement this there.
