### ISSUE TITLE
Spack build system is broken

### ISSUE THREAD

**Issue by giordano** [eth-cscs/reframe#2466]
Whenever I run a benchmark using Spack as build system, installation of  packages (if not already present in the environment) fails with
```
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/home/mose/repo/spack/lib/spack/llnl/util/tty/log.py", line 756, in _writer_daemon
    with keyboard_input(stdin) as kb:
  File "/home/mose/repo/spack/lib/spack/llnl/util/tty/log.py", line 239, in __enter__
    if not self._is_background():
  File "/home/mose/repo/spack/lib/spack/llnl/util/tty/log.py", line 164, in _is_background
    return _is_background_tty(self.stream)
  File "/home/mose/repo/spack/lib/spack/llnl/util/tty/log.py", line 67, in _is_background_tty
    os.getpgrp() != os.tcgetpgrp(fd)
--- rfm_SombreroBenchmark_build.err --- 
------------------------------------------------------------------------------
```
`git bisect` points to https://github.com/eth-cscs/reframe/commit/c466fef35019a18abf020856f31289a9b04fe619 from #2383, which looks relevant.

**Comment by giordano** [comment]
I've got a simple reproducer:
```python
import reframe as rfm
import reframe.utility.sanity as sn

@rfm.simple_test
class LibtreeTest(rfm.RegressionTest):
    valid_systems = ['*']
    valid_prog_environs = ['*']
    build_system = 'Spack'
    executable = 'libtree'
    executable_opts = ['--version']

    @run_before('compile')
    def setup_build_system(self):
        self.build_system.specs = ['libtree@3.1.0']

    @run_before('sanity')
    def set_sanity_patterns(self):
        self.sanity_patterns = sn.assert_found(r'3.1.0', self.stdout)
```

I left some more comment in https://github.com/spack/spack/issues/17471#issuecomment-1064084256.  This may well be a bug in CPython (a function not documented to throw is erroring out), but it was lifted only recently in ReFrame by the commit mentioned above, so it'd be great if it was possible to keep Spack integration working on the ReFrame side :slightly_smiling_face:

**Comment by vkarak** [comment]
Hi @giordano, thanks for the reproducer. I haven't had the time to look into the issue yet. What puzzles me is that this commit simply added support for piping stdin in the `run_command()` and this is only used by the LSF scheduler backend. I will have a deeper look and get back to you.
