### ISSUE TITLE
Adapt OpenACC+MPI GPU test

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#247]
MCH will provide an updated version of the test's source code:

https://github.com/eth-cscs/reframe/blob/master/cscs-checks/prgenv/src/gpu_direct_acc.f90

Also the filename is not accurate.

**Comment by lxavier** [comment]
see https://github.com/eth-cscs/reframe/pull/281

**Comment by vkarak** [comment]
Hi @lxavier, I'd suggest putting a reference in the corresponding pull request's description rather than here (Github tracks the references automatically). Also, if your PR fixes this issue, simply put in the description the following text `Fixes #247`, so that Github will automatically close the issue as soon as we merge it.

**Comment by vkarak** [comment]
Quoting from @lxavier about running the test:

> nothing special I would start to run it on one node (e.g. 8 GPUs on Kesch) just did srun -n 8
The important thing is to load the module that we use. Since our new module generator is not yet ready you could use the module file on /project /project/c14/install/kesch/cosmo5/modules_fortran_gpu_double.env
