### ISSUE TITLE
Investigate dynamic module creation by a ReFrame test

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#255]
Given the COSMO complexity, MCH wants to generate on-the-fly a module file (by running a shell script), which will take care of the environment setup of the test. The ReFrame test will load then this environment.

We need to investigate this scenario and if it can be supported from the current framework. What changes would be needed to make it feasible? Alternatives?

**Comment by ajocksch** [comment]
import os
from datetime import datetime

import reframe.utility.sanity as sn
from reframe.core.pipeline import RegressionTest

import reframe.utility.os_ext as os_ext

class HelloWorldBaseTest(RegressionTest):
    def __init__(self, **kwargs):
        super().__init__('environment',
                         os.path.dirname(__file__), **kwargs)

        self.modules = ['my_testmod']

        if self.current_system.name in ['dom', 'daint']:
            self.modules += ['gcc/6.1.0']

        self.variables = {'CRAYPE_LINK_TYPE': 'dynamic'}

        self.prgenv_flags = {}

        self.descr = 'environment'

        self.valid_systems = ['daint:gpu', 'daint:mc', 'dom:gpu', 'dom:mc',
                              'kesch:cn', 'kesch:pn', 'leone:normal',
                              'monch:compute']

        self.valid_prog_environs = ['PrgEnv-cray', 'PrgEnv-gnu',
                                    'PrgEnv-intel', 'PrgEnv-pgi']

        self.compilation_time_seconds = None

        self.maintainers = ['XX', 'YY']

        self.num_tasks = 1
        self.num_tasks_per_node = 1
        self.num_cpus_per_task = 1

#        self.prebuild_cmd = ['/scratch/ajocksch/hello_env/module_copy.sh']
#        self.pre_run = ['/scratch/ajocksch/hello_env/module_copy.sh']

    def setup(self, partition, environ, **job_opts):

        os_ext.run_command('/scratch/ajocksch/hello_env/module_copy.sh')

        result = sn.findall(r'The current value is: 1', self.stdout)

        self.sanity_patterns = sn.all(
            sn.chain([sn.assert_eq(sn.count(result), 1)])
        )

        super().setup(partition, environ, **job_opts)

    def compile(self):
        super().compile()


def _get_checks(**kwargs):
    return [HelloWorldBaseTest(**kwargs)]

**Comment by vkarak** [comment]
Why the `sanity_patterns` should set in `setup()`?

**Comment by vkarak** [comment]
@ajocksch Could you please clean up this example, so that we can close this issue?

**Comment by vkarak** [comment]
Here is another example of a run-only test emulating a dynamic creation of a module. This test copies a test module file from ReFrame's unit tests to the directory of the test, updates the module path and lets ReFrame load it. The sanity function checks that the module is actually loaded by checking that a variable set by the module can be read successfully:

```python
import os
from datetime import datetime

import reframe.utility.sanity as sn
from reframe.core.pipeline import RunOnlyRegressionTest
from reframe.core.modules import get_modules_system

import reframe.utility.os_ext as os_ext


class DynamicModuleTest(RunOnlyRegressionTest):
    def __init__(self, **kwargs):
        super().__init__('dynmod_check', os.path.dirname(__file__), **kwargs)
        self.modules = ['my_testmod']
        self.valid_systems = ['*']
        self.valid_prog_environs = ['*']
        self.executable = 'echo $TESTMOD_FOO'
        self.sanity_patterns = sn.assert_found('FOO', self.stdout)
        self.sourcesdir = None

    def setup(self, partition, environ, **job_opts):
        os_ext.run_command(os.path.expandvars(
            'cp  $HOME/Devel/reframe/unittests/modules/testmod_foo %s/my_testmod' % self.prefix),
            check=True)

        # The way this is done will be changed in the upcoming releases.
        # This step is not needed if the target directory is already at the MODULEPATH
        get_modules_system().searchpath_add(self.prefix)
        super().setup(partition, environ, **job_opts)


def _get_checks(**kwargs):
    return [DynamicModuleTest(**kwargs)]
```

Closing the issue, since we proved that this is possible to achieve with ReFrame, despite using internal APIs.
