### ISSUE TITLE
Os error when running with async execution policy

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#291]
The error is `OS error: [Errno 39] Directory not empty` and it seems to be related to the removal of directories.

**Comment by vkarak** [comment]
@teojgo Can you please comment how to reproduce and on which system?

**Comment by vkarak** [comment]
It fails consistently also for me on Dom:

```
./reframe.py -C config/cscs.py -c cscs-checks/libraries/magma/magma_checks.py --exec-policy=async -r
```

**Comment by teojgo** [comment]
As already discussed, @vkarak you can close this issue since we cannot reproduce and we have not observed it happening again.

**Comment by vkarak** [comment]
I can't reproduce it either. Seems like a transient system issue. Closing it.

**Comment by vkarak** [comment]
I am reopening this, cos this is still happening from time to time.

**Comment by teojgo** [comment]
This issue seems to be related to the network file system. They had the same problem in Easybuild, https://github.com/easybuilders/easybuild-framework/pull/353.

**Comment by vkarak** [comment]
Perhaps we can replace `rmtree` with our more persistent version as Easybuild does.
