### ISSUE TITLE
Create a 'Make' build system

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#297]
A build system that will use `make` for compiling the source code inside a directory. It will be used automatically by the framework if `sourcepath` refers to a directory and no build system is specified.

**Comment by teojgo** [comment]
While preparing the cudamemtest check, I wanted to use `Make` with a nondefault target. It would be nice if the new build system had also an option to specify a target to the Makefile directly, without having to pass it to the `options` during the compilation.

**Comment by vkarak** [comment]
It has an `options` attribute where you can pass anything to the make invocation. Check my PR. I don't think it makes sense to add a separate attribute just for specifying targets.

**Comment by vkarak** [comment]
Closed by #340.
