### ISSUE TITLE
Update G2G latency tests

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#327]
The current latency test does not really measure latency, but it measures bandwidth.
Instead of using `osu_bw` we should be using `osu_latency`. Especially, because the latter uses a different algorithm than the former.

**Comment by vkarak** [comment]
@victorusu Can you please put a link to the OSU benchmarks documentation?

**Comment by victorusu** [comment]
Sure. The link to OSU documentation is
http://mvapich.cse.ohio-state.edu/static/media/mvapich/README-OMB.txt
