### ISSUE TITLE
ddt_check_Cuda fails after maintenance

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#328]
FAILURE INFO for ddt_check_Cuda 

```
  * System partition: daint:gpu
  * Environment: PrgEnv-gnu
  * Stage directory: /scratch/snx3000/piccinal/reframe/stage/gpu/ddt_check_Cuda/PrgEnv-gnu
  * Job type: batch job (id=7993758)
  * Maintainers: ['MK', 'JG']
  * Failing phase: sanity
  * Reason: sanity error: pattern `MPI implementation' not found in `ddtreport.txt'
```

**Comment by vkarak** [comment]
@teojgo As far as I understood you are also working on that, aren't you?

**Comment by jgphpc** [comment]
>    [1]@teojgo As far as I understood you are also working on that, aren't
>    you?

I will do it:
self.maintainers = ['MK', 'JG']

**Comment by vkarak** [comment]
Ok, marked as important and moved it to the current sprint.

**Comment by teojgo** [comment]
@jg I managed to make it work by enforcing use of cudatoolkit 8.0

**Comment by jgphpc** [comment]
During daint's maintenance, cuda driver was updated to support cuda/9 (was 375.74, is 384.11 now) but cudatoolkit/8.0.61_2.4.3-6.0.4.0_3.1__gb475d12
remains default => setting ALLINEA_FORCE_CUDA_VERSION=8.0 for daint checks.
