### ISSUE TITLE
Module loading/unloading appears not to work

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#34]
Hi,

I have some tests I would like to run with only the Cray compiler, via the `PrgEnv-cray` programming environment. My settings include:
```
                'PrgEnv-cray': {
                    'type': 'ProgEnvironment',
                    'modules': ['PrgEnv-cray'],
                    'cc':  'cc',
                    'cxx': 'CC',
                    'ftn': 'ftn',
```
and in the test script I have
```
        self.valid_prog_environs = ['PrgEnv-cray']
```
However, when I attempt to run the test with the `PrgEnv-intel` module loaded, ReFrame appears to make no attempt to swap or unload any modules before compiling the code (which then fails). If I manually switch to `PrgEnv-cray` and then invoke the test, it compiles and runs. (Of course this approach is impractical if running a series of tests which require different programming environments.)

The documentation claims that ReFrame is aware of conflicting modules and unloads/swaps them as necessary in order to achieve the desired programming environment. Any ideas what I am doing wrong such that this feature seems not to be active?

Thanks in advance.

**Comment by victorusu** [comment]
Dear Brian,

Can you please share with us the version of reframe you are using the `reframe.log` file created when you run reframe for this specific check?

We will be looking for similar lines as the ones below around line 60

```
[XXXX] debug: testname@partition using PrgEnv-cray: loading environment for the current partition
[XXXX] debug: testname@partition using PrgEnv-cray: loading test's environment
[XXXX] debug: testname@partition using PrgEnv-cray: executing OS command: modulecmd python show PrgEnv-cray
[XXXX] debug: testname@partition using PrgEnv-cray: executing OS command: modulecmd python unload PrgEnv-intel
[XXXX] debug: testname@partition using PrgEnv-cray: executing OS command: modulecmd python load PrgEnv-cray
```

**Comment by vkarak** [comment]
Hi @bcfriesen,

Have you set the `modules_system` backend to `tmod` in your configuration file? Have a look [here](https://eth-cscs.github.io/reframe/configure.html#system-configuration).

**Comment by bcfriesen** [comment]
Ah, yes the undefined `modules_system` setting was the problem. After I set that to `tmod`, it worked as expected. I'll close this issue, thanks @victorusu @vkarak.

**Comment by vkarak** [comment]
Great! Actually, we are going to update the settings file of the tutorial, because this option doesn't show up there, while it should have, and this perhaps is a bit confusing.
