### ISSUE TITLE
Is there a way to use the same filename for stdout and stderr?

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#345]
Is there a way to use the same filename for stdout and stderr ?

```
#SBATCH --output=
#SBATCH --error=
```

**Comment by vkarak** [comment]
Currently not. Why would you need that?

**Comment by jgphpc** [comment]
If i get a message, for example:

`WARNING: iMaxRung parameter ignored. MaxRung is 30`

it's difficult to know when it appears in the duration of the job because the stdout is in a different file.
But that's fine, i can live without it, just wanted to be sure.

**Comment by vkarak** [comment]
You can use the sanity functions to look into stderr. I don't know if this can help you.

**Comment by jgphpc** [comment]
Thanks, close it please.
