### ISSUE TITLE
NetCDF test using the COSMO environment

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#351]
Quoting from @lxavier:

>             module load craype-haswell
>             module load craype-accel-nvidia35
>             module load craype-network-infiniband
>             module load netCDF-Fortran/4.4.4-CrayCCE-17.06
>             module switch mvapich2_cce/2.2rc1.0.3_cuda80 mvapich2gdr_gnu/2.2_cuda_8.0
>             module load gcc/5.4.0-2.26
>             module load cmake/3.9.1
>
> # same as what we do for cosmo
> NETCDFL="-L$EBROOTNETCDFMINFORTRAN/lib -lnetcdff -L$EBROOTNETCDF/lib64 -lnetcdf"
> NETCDFI=-I$EBROOTNETCDFMINFORTRAN/include
> ftn -v $NETCDFI $NETCDFL simple_xy_wr.f90
> srun ./a.out                                                      [92/285]
> *** Test : writing example netcdf file simple_xy.nc
>  Result : OK
>
>
>
> With PGI I tried
>
> module load PrgEnv-pgi/18.4_gdr
> mpif90 simple_xy_wr.f90
> PGF90-F-0004-Unable to open MODULE file netcdf.mod (simple_xy_wr.f90: 21)
> PGF90/x86-64 Linux 18.4-0: compilation aborted
>
> But I can’t link.

The source file is communicated privately.

**Comment by jgphpc** [comment]
seems to be done with: libraries/io/netcdf_compile_run.py

```
ls /apps/common/UES/reframe/resources/netcdf/ 
netcdf_read_write.c
netcdf_read_write.cpp
netcdf_read_write.f90
```
