### ISSUE TITLE
need an option to run without "srun"

### ISSUE THREAD

**Issue by jfavre** [eth-cscs/reframe#4]
Visit uses the name of the scheduler "srun", as an option to its own scheduler. Thus, instead of running as a typical simulation such as:

srun visit [options]

I run it in the following way:

visit [options] -l srun

currently, I did not find a way to accomplish this with reframe. @vkarak has seen the demonstration

**Comment by vkarak** [comment]
Thanks @jfavre for reporting this.

I'll copy that to our internal bug tracking.

**Comment by vkarak** [comment]
Hi @jfavre, this is now fixed in 2.5 release. The users can easily create new custom launchers. We also provide a launcher for VisIt. Have a look in the documentation [here](https://eth-cscs.github.io/reframe/writing_checks/#custom-launchers) for more details.
