### ISSUE TITLE
'logdir' system attribute in configuration file does not work correctly

### ISSUE THREAD

**Issue by mand35** [eth-cscs/reframe#419]
The behavior with the logdir handling seems to be strange. If I define the `logdir` option at the machine specification in reframe/settings.py, it sets that directory for `Stage dir` and `Output dir`, but not for `Perf. logging prefix`. Using the `perflogdir` option instead in the reframe/settings.py has no effect. 

Using the command line option `--perflogdir` seems to work fine.

**Comment by vkarak** [comment]
@mand35 You are right this is a bug. Thanks for spotting!

How to reproduce:

1. Set `logdir` as a system attribute in the configuration file:
   ```
                'logdir': '/foo/logs',
   ```
2. Run reframe:
   ```
   ./bin/reframe -l
   ```

   ```
   ./reframe.py: stage and output refer to the same directory; if this is on purpose, please use also the `--keep-stage-files' option.
   ```
