### ISSUE TITLE
`output` and `stage` folder are not created under `prefix`

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/reframe#446]
I have realised that although I set `--prefix ...`, the `output` and `stage` folders get created under the default location for the system where I run (e.g.: `$SCRATCH/regression/production/...` on Piz Daint). 
Of course I can set them manually with `--output` and `--stage`, but is this behaviour expected?

**Comment by vkarak** [comment]
@lucamar Can you please paste the exact command you are using? If you use `--prefix` in conjunction with a more specific options for one of the other two directories, the more specific options will have precedence. This is especially true if you use an execution mode that passes such an option.

**Comment by lucamar** [comment]
@vkarak Thanks for your reply, actually I'm using it with `--keep-stage-files --save-log-files`:
```
nohup reframe --prefix /scratch/snx1600/lucamar/2018_09_07 --account usup --keep-stage-files --save-log-files --mode production --max-retries=3 -r
```

**Comment by vkarak** [comment]
The `production` mode passes specifically the `--output` and `--stage` options, that's why this is happening; `--prefix` will have no effect. I suggest not using the `production` mode at all.

**Comment by vkarak** [comment]
@lucamar Can I close this now?

**Comment by lucamar** [comment]
Sure, thanks
