### ISSUE TITLE
The build_system.srcdir is not set if build system is defined

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#454]
This was introduced when #447 was merged and is probably caused by moving the assignment inside the if block in https://github.com/eth-cscs/reframe/blob/24ec3001a01a3e9d16f5a996cab7b593cb718a43/reframe/core/pipeline.py#L940

**Comment by vkarak** [comment]
@teojgo Can you provide a minimal reframe test that triggers the error?

**Comment by teojgo** [comment]
Actually I was setting the `build_system.srcdir` directly in the scorep tests. Before #454 this worked because even when `self.build_system` was set, it was replaced by  `sourcepath`. In #454 the `self.build_system.srcdir` is given the value of `self.sourcepath` only when the detection of the build system is performed by ReFrame.
