### ISSUE TITLE
Support for tests that depend on each other

### ISSUE THREAD

**Issue by boegel** [eth-cscs/reframe#483]
I'm interested in looking into whether ReFrame is a good tool for supporting the EasyBuild (http://easybuilders.github.io/easybuild/) regression test, in which we rebuild each easyconfig in the central repository prior to making a new release.

Since easyconfigs depend on each other, this requires being able to specify dependencies between tests, e.g. test C depends on test A & B having run (and succeeded).

As far I can tell, this is not supported yet by ReFrame right now?

cc @victorusu @gppezzi

**Comment by vkarak** [comment]
Hi @boegel, test dependencies are currently not supported, but it is a feature we have been thinking to implement for a while. We have also some use cases in mind, regarding using ReFrame as a CI tool.
