### ISSUE TITLE
Add regression test to check the environment

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/reframe#524]
We have recently experienced several changes in the environment on the TDS system (e.g.: new NVIDIA driver, new Linux kernel, new Programming Environment...) and the list of modules loaded at the time we build and run applications unfortunately is not enough to have a full picture.

It would be therefore useful to have a test `environment_check` that does at least the following:
```
rpm -qa
env
module -t avail 2>&1
```
The data can be compared against a reference list of `rpm`, `env` and `module` commands (filtering default ones in the last case, for instance) and raise a `WARNING` or `FAIL` in case of a mismatch.

**Comment by victorusu** [comment]
We should also check the compute node images. The proper command for that is
`rpm --root=$(findmnt -t squashfs /dev/loop3 -o target -f -n) -qa | sort`
