### ISSUE TITLE
ScoreP MPI/OpenMP tests are failing on Daint

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#525]
```
FAILURE INFO for scorep_mpi_omp_C (for the last of 2 retries)
  * System partition: daint:gpu
  * Environment: PrgEnv-gnu
  * Stage directory: None
  * Job type: batch job (id=-1)
  * Maintainers: ['MK', 'JG']
  * Failing phase: setup
  * Reason: caught framework exception: could not load module Score-P/4.0-CrayGNU-18.08-cuda-9.1
```

**Comment by jgphpc** [comment]
The MODULEPATH is: /apps/daint/UES/jenkins/6.0.UP07/gpu/easybuild/`tools`/modules/all
Could that explain the issue ?

**Comment by vkarak** [comment]
@jgphpc The problem is that the module names differs on the hybrid nodes. I'm on it.

**Comment by vkarak** [comment]
@jgphpc I did a further investigation and the problem is the following:

```
module load daint-gpu
module load Score-P/4.0-CrayIntel-18.08
```

```
libunwind(3):ERROR:105: Unable to locate a modulefile for 'libunwind/.1.2.1'
```

It seems like an installation problem. Should I open an issue there?

**Comment by jgphpc** [comment]
yes

**Comment by vkarak** [comment]
Opened issue in production repo: https://github.com/eth-cscs/production/issues/898

**Comment by jgphpc** [comment]
Installed libunwind manually (jenkins won't do it even with --force).
All versions of Score-P should load fine now (both daint-gpu and daint-mc)
