### ISSUE TITLE
Revisit the naming convention of the stage directories of retries

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#536]
After some real situations of production runs, I think that the current naming convention is confusing and unnatural:

```
/path/to/stage/sys/part/env/testname
/path/to/stage_1/sys/part/env/testname
/path/to/stage_2/sys/part/env/testname
```

This convention also increases the i-node count without a reason. I suggest changing to the following, which more natural and more intuitive:

```
/path/to/stage/sys/part/env/testname_0
/path/to/stage/sys/part/env/testname_1
/path/to/stage/sys/part/env/testname_2
```

We can agree on the suffix, but any change other in the last component of the path will be confusing.

**Comment by vkarak** [comment]
@eth-cscs/reframe-devteam Can sb take this? I raised its priority, cos it makes us hit the i-node limit of scratch.

**Comment by omlins** [comment]
As agreed offline, we adopted the following convention:
```
/path/to/stage/sys/part/env/
/path/to/stage/sys/part/env/testname_retry1
/path/to/stage/sys/part/env/testname_retry2
```
