### ISSUE TITLE
Add GREASY checks

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#539]
We need to add four GREASY checks that encompass the four supported use cases in the user portal (https://user.cscs.ch/tools/high_throughput/)

- Single core tasks
- OpenMP
- MPI only tasks
- MPI+OpenMP tasks

**Comment by jgphpc** [comment]
@victorusu can this issue be closed ?
looks like you wrote a check:
https://github.com/eth-cscs/reframe/blob/master/cscs-checks/apps/greasy/greasy_check.py

**Comment by victorusu** [comment]
Sure!
