### ISSUE TITLE
Set `exclusive_access` to all tests for Kesch

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#589]

**Comment by teojgo** [comment]
The issue can be closed. The only remaining tests are on the private repository. Comments were made at the issues for the individual tests.

**Comment by vkarak** [comment]
@teojgo Could we have PR in the private repo that sets this flags and fixes the issue completely?

**Comment by teojgo** [comment]
@vkarak There are individual issues for each of the tests that need to be adapted anyway.

**Comment by vkarak** [comment]
Ok, we can close this then.
