### ISSUE TITLE
Add command-line options for specifying a report output file and the type of the report

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#653]
Proposed options:

- `-F X` or `--file X` for output file
- `--report X` for specifying the type. Default type should be the standard reframe report, i.e., the summary report produced at the end or a bit augmented to record also the successes. We could then omit completely the `reframe.out` file and just store the generated report file in the production and maintenance execution modes.

**Comment by jgphpc** [comment]
Is it done already here:
https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/cli.py#L183  ?

**Comment by vkarak** [comment]
Indeed, it was addressed by #1377.
