### ISSUE TITLE
'keep_files' parameter can not save directories

### ISSUE THREAD

**Issue by ZQyou** [eth-cscs/reframe#668]
`keep_files` cannot save directories as described in the reference
```
List of files to be kept after the test finishes.

By default, the framework saves the standard output, the standard error and the generated shell script that was used to run this test.

These files will be copied over to the framework’s output directory during the cleanup() phase.

Directories are also accepted in this field.

Relative path names are resolved against the stage directory.
```
In `core/pipeline.py`,  the function `_copy_to_outputdir` calls `shutil.copy`  which can not copy directories.

**Comment by vkarak** [comment]
@ZQyou Thanks for reporting this. You are right. I'll turn that into a documentation bug and open a feature request for supporting directory copying in `keep_files`.

**Comment by teojgo** [comment]
@ZQyou can you check that #673 addresses your problem with the copying of directories?

**Comment by ZQyou** [comment]
@teojgo  Thank you. My colleague has already checked #673. That is almost exactly the same as his commit that fixed the issue.

**Comment by teojgo** [comment]
@ZQyou thanks for the feedback!
