### ISSUE TITLE
Support syslog handler in logging.py

### ISSUE THREAD

**Issue by ZQyou** [eth-cscs/reframe#671]
We use splunk + syslog for performance check and visualization instead of using special log server. Adding syslog handler  in `logging.py` seems trivial and I have done this on my side:
```
def _create_syslog_handler(handler_config):
    return logging.handlers.SysLogHandler(address = '/dev/log')

def _create_stream_handler(handler_config):
    stream = handler_config.get('name', 'stdout')
    if stream == 'stdout':
            hdlr = _create_file_handler(handler_config)
        elif handler_type == 'filelog':
            hdlr = _create_filelog_handler(handler_config)
        elif handler_type == 'syslog':
            hdlr = _create_syslog_handler(handler_config)
        elif handler_type == 'stream':
            hdlr = _create_stream_handler(handler_config)
...
```

**Comment by vkarak** [comment]
Thanks @ZQyou, I was thinking the same thing these days, cos several sites use syslog and some elastic search to pipe the syslog into. Would you mind doing a PR for that, since you already have it running?

**Comment by ZQyou** [comment]
Sure, I will work on that.
