### ISSUE TITLE
Explain more the scoped dictionaries in the documentation

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#68]
They can be quite useful also when writing tests, so we should also present some advanced examples.

Internal issue: https://madra.cscs.ch/scs/reframe/issues/286

**Comment by jgphpc** [comment]
> This is a special type of dictionary that we call scoped dictionary, because it defines scopes for its keys. 
[writing-a-performance-test](https://reframe-hpc.readthedocs.io/en/stable/tutorial.html#writing-a-performance-test)
