### ISSUE TITLE
Add Bash completion support to ReFrame

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#725]
That will be quite useful for selecting tests.

**Comment by shahzebsiddiqui** [comment]
Try the ``argcomplete`` package. See https://buildtest.readthedocs.io/en/devel/setup.html#setting-up-auto-complete-on-buildtest-arguments this on how to do arg-completion on bash/sh and tcsh/csh.

**Comment by vkarak** [comment]
Thanks @shahzebsiddiqui for your suggestion!
