### ISSUE TITLE
Print the number of nodes required by a test in the detailed listing

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#746]

**Comment by teojgo** [comment]
@vkarak  I do not know if this is possible since the number of tasks can be different between system 
and that information is not available at listing.

**Comment by vkarak** [comment]
If the difference is per system, then there is no problem. The problem is only if you set different `num_tasks` per partition and/or programming environment. Nonetheless, I think it's good if we at least print if a test is flexible or not.
