### ISSUE TITLE
Module mapping file and corresponding command line option

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#76]
A way should be defined for specifying module mappings. The most straightforward is to have files, that the user could specify in the command line, in the following form:

```
gromacs GROMACS/2016.1
amber Amber/16
```

Internal issue: https://madra.cscs.ch/scs/reframe/issues/552

**Comment by rsarm** [comment]
@eth-cscs/reframe-devteam 
@vkarak  and I were discussing a bit on how to format the file to specify module mappings. Could you offer some suggestions on that? We were considering something like this
```
gromacs: GROMACS/2016.1, GROMACS/2017.1
amber: Amber/16
```

**Comment by vkarak** [comment]
@rsarm We should also support line comments. Lines starting with a `#` must be ignored.

**Comment by rsarm** [comment]
@vkarak , In the morning, with @victorusu we discussed the idea of the mapping file's format to be a per-system scoped dictionary. I also find it convenient to have mappings separated by systems in a single file. What do you think?

**Comment by vkarak** [comment]
Yes, we have done such a discussion with @victorusu before. But I think this is a different issue. We should not confuse it with this one. If you extend the interface of the `ModulesSystem` class with a method `load_mapping_from_file()`, it doesn't matter who is calling that. In this issue it's the CLI that will be calling it based on a command-line option. It's another issue to add support for different mapping files per system, in which case this method will be called when reading the site configuration. In general, the mapping may be set in the following places with decreasing order of priority:

1. Command-line option specifying explicit mappings (that's issue #45)
2. Command-line option specifying a mapping file (this is the current issue)
3. Configuration option for setting the mapping file per system (I will create a new issue for that)

**Comment by vkarak** [comment]
The important thing here is the implementation of the `load_mapping_from_file()` method. One thing we should decide is the syntax of the mapping file and another thing is the behaviour of the method. For example, what happens there is already a mapping and somebody calls this method? Does it wipe out the existing mapping and creates a totally new or does it just update the current one changing or adding new values?
