### ISSUE TITLE
Add support for modules version 3.1

### ISSUE THREAD

**Issue by alchemroz** [eth-cscs/reframe#784]
Dear developers, as pointed out by Rafael Sarmiento in a previous issue ReFrame does not support Tcl/modules 3.1, but it start only from Tcl 3.2. I work in Cineca in Bologna (Italy) and in our main clusters (marconi/galileo) we have still Tcl 3.1.6. Could you please to add the support for this version ?

Thanks,
Simone

**Comment by vkarak** [comment]
Thanks, Simone for pointing this out. For the moment we'll add a Tmod version check, so that we issue a better error message. We have also discovered that versions 4.1 and higher are supported from Tmod4.
