### ISSUE TITLE
Mixed out/err error message

### ISSUE THREAD

**Issue by aurianer** [eth-cscs/reframe#789]
In error messages related to compilation, the file names for stderr and stdout are interchanged.

Example :

```
  * Reason: build error: standard error can be found in `/users/aurianer/projects/ssl-microbench
/gemm/stage/ault/amdvega/builtin-gcc/GemmTest_blis/rfm_GemmTest_blis_build.out', standard 
output can be found in `/users/aurianer/projects/ssl-microbench/gemm/stage/ault/amdvega/builtin-
gcc/GemmTest_blis/rfm_GemmTest_blis_build.err'
------------------------------------------------------------------------------
```

Please note that the *.out and *.err have the correct content, the mistake lies solely in the error message.

Inspecting `exceptions.py` reveals that the variables stdout and stderr are interchanged.
https://github.com/eth-cscs/reframe/blob/master/reframe/core/exceptions.py#L117-L118

**Comment by aurianer** [comment]
I will submit a PR

**Comment by vkarak** [comment]
Thanks @aurianer for reporting this. Since you're going to submit a PR, I'll assign it to you.
