### ISSUE TITLE
Alloc speed check reported timings seem problematic

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#802]
Using Clang 7 and `-O0` I get negative timings:

```
==============================================================================
PERFORMANCE REPORT
------------------------------------------------------------------------------
AllocSpeedTest_no
- tresa:login
   - PrgEnv-clang
      * time: 0.441987 s
------------------------------------------------------------------------------
AllocSpeedTest_2M
   - PrgEnv-clang
      * time: -0.332334 s
------------------------------------------------------------------------------
```

Using `-O3`, I get zero seconds.

```
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

**Comment by toxa81** [comment]
It's because somebody changed the test. Originally there was malloc(). Malloc() doesn't touch the memory. Somebody changed it to new[], which touches the memory. So the whole test has become wrong

**Comment by teojgo** [comment]
@toxa81 Thanks for the response, will fix it so that it uses malloc.

**Comment by vkarak** [comment]
@toxa81 Thanks for the comment. You are right: `new` creates the objects as well. Original version here:

https://github.com/eth-cscs/reframe/pull/597/commits/fee7c73cd3b78145814b18c0a9187e57f401de27

The changes were done due to my review; my bad.
