### ISSUE TITLE
out-of-the-box user experience "could not auto-detect system"

### ISSUE THREAD

**Issue by boegel** [eth-cscs/reframe#832]
Just took `reframe` for a quick spin (without checking the documentation, I must admit), and I think there's some low hanging fruit to create a better initial user experience.

After checking `reframe --help`, I wanted to check which tests are available out-of-the-box (if any):

```
$ reframe -l
/software/ReFrame-HPC/2.18/bin/reframe: could not auto-detect system; please use the `--system' option to specify one explicitly
```

Same output for `reframe --show-config`.

One minor annoyance here is the full `reframe` part being printed, I don't think that's really necessary to be helpful?

I couldn't find a `--list-systems` option based on the `--help` output, and a naive attempt to use `--system localhost` failed miserably...

Maybe a pointer to the documentation should be spit out when `reframe` noticed it's "starting from scratch" (no systems defined yet), or simply default to using `localhost` (if that's an option, for example by auto-detecting # available cores)?

**Comment by vkarak** [comment]
I agree, this can be a bit annoying. The magic work for the `--system` option is `--system=generic`, but `localhost` would make more sense. This part of "auto-detection" can certainly be improved.
