### ISSUE TITLE
Cancel job after a certain queueing time

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#881]
This a feature request coming from @mand35:

> We want to submit our jobs daily. But in some cases nodes can be occupied for longer, than we would like to skin these data points and neglect these runs for nodes which are busy the whole day. We do not want to queue up more and more jobs for one node.

**Comment by mand35** [comment]
This could be similar to the SLURM option `--deadline`, e.g. with `(datetime.timedelta(days=0,hours=24)+datetime.datetime.now()).isoformat(timespec='seconds')`
Thus we can schedule daily jobs and prevent queuing up more and more jobs in our multi day partition.

**Comment by vkarak** [comment]
@mand35 When the time out is reached,  do you want to mark the test as a failure or not?
Similarly, @bcfriesen, in relation to #1049, how would you consider this timeout? I am about to merge #1099, where currently this timeout is treated as a failure, but I'm not sure what would be more reasonable for your cases?

**Comment by bcfriesen** [comment]
Hi @vkarak - I think #1099 is a useful feature and should be merged. But in relation to #1049, it's not clear to me that #1099 fixes the problem. I would almost say that we would want the *opposite* behavior, i.e., ReFrame should trust that the job will eventually run even if `sacct` reports `ReqNodeNotAvail`. (That is the current behavior of NERSC's fork of ReFrame, where I simply removed `ReqNodeNotAvail` from the list of cancel reasons altogether.) Although I can see how that approach may lead to trouble in the case that `ReqNodeNotAvail` is a more meaningful result than it typically is on Cori.

**Comment by vkarak** [comment]
@bcfriesen, Yes it does not fix #1049, but my idea, as discussed also in that issue, is to add a configuration option that will essentially do what your patch does and then you can also add a deadline in your tests to make them future proof, if `ReqNodeNotAvail` becomes more meaningful. That's where #1099 comes into play in that scenario ;-)

**Comment by bcfriesen** [comment]
Ahh OK, sorry I misunderstood. Yes that sounds great, that would address our issue!
