### ISSUE TITLE
Add option to use login shell to build executables

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/reframe#882]
Currently `ReFrame` invokes `/bin/bash` without `-l` in the build scripts. 
It could be useful to add an option to select a login shell as well if needed, i.e. using the option `-l` of the `bash` command.

**Comment by lucamar** [comment]
Node `tsa-cn018` has been rebooted with `Modules 4.0.0` for testing:
```
$ man module | tail
SEE ALSO
       modulefile(4)
COPYRIGHT
       1996-1999 John L. Furlani & Peter W. Osel, 1998-2017 R.K.Owen, 2002-2004 Mark Lakata, 2004-2017 Kent Mein, 2016-2017 Xavier Delaruelle
4.0.0                                                                          2017-10-16                                                                      MODULE(1)

```
$ ls -ltrh /cm/local/apps/environment-modules/4.0.0/libexec/
total 304K
-rwxr-xr-x 1 root root 134K Dec 10  2017 modulecmd-compat*
-rwxr-xr-x 1 root root 167K Dec 10  2017 modulecmd.tcl*
```

**Comment by vkarak** [comment]
@lucamar Actually this is an inconsistency with what we generate for jobs. So we can always emit `-l` for the build scripts as well. Do you think this is going to hurt somewhere?

**Comment by lucamar** [comment]
@vkarak That's a good idea, I don't think that it's going to hurt and it will make build easier.
