### ISSUE TITLE
Adapt ReFrame to test non-default Cray Programming Environments

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/reframe#895]
Whenever a non-default Cray Programming Environment is installed on a Cray system, in order to test non-default modules one needs to do the following steps to update the environment:
```
module load cdt/19.08
[ load necessary modules] 
export LD_LIBRARY_PATH=$CRAY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
```
See https://user.cscs.ch/computing/compilation/#piz-daint-xc50-xc40-, section "Using non-default Programming Environments".

I could not find a way to update `LD_LIBRARY_PATH` within individual ReFrame checks, without manually editing each check: one needs to update the variable after loading the modules to run the checks, therefore updating the variable in the settings file is not an option, unfortunately.

**Comment by gppezzi** [comment]
One potential alternative could be to add `-add-rpath` to the build flags.

The `module load cdt` can be issued in the terminal before launching reframe, so this step doesn't necessarily need to be done by ReFrame. Is that correct?

**Comment by lucamar** [comment]
@gppezzi Yes, the first `module load cdt/...` will be inherited by ReFrame.

**Comment by vkarak** [comment]
@gppezzi Wouldn't that mean that one would have to recompile the whole s/w stack? I think this is a valid feature request, but not high priority.

**Comment by gppezzi** [comment]
The idea here is to run only the PE checks and not necessarily the entire regression suite.

Use case is: when we install a new PE without changing the defaults and without rebuilding the software stack.
