### ISSUE TITLE
Submit jobs from the stage directory

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#91]
Currently, we submit jobs from the directory where ReFrame is launched and we insert a `cd /to/stagedir` in the generated script. This creates some complications as described in #35 and leads to a bit cumbersome tests and, more importantly, to not easily reproducible problems. Submitting jobs from the stage directory will make the generation of the job script more straightforward and the job script itself more readable. Also, with the deprecation of the `Job`'s `pre_run` attribute, there is no way to obtain and set a variable using the stage directory, unless the `self.stagedir` becomes a deferrable.

**Comment by vkarak** [comment]
@victorusu Do you think that the Slurm backend should also pass the `--workdir=<stagedir>` option in the job script, besides submitting it from the stagedir? I think this will allow to submit the script from any directory, but it is Slurm-specific.

**Comment by victorusu** [comment]
Or we set the `--workdir` or we issue the command `cd <stage-dir>`. 

I think that `cd <stage-dir>` makes the engine for job script more "scheduler agnostic".

**Comment by vkarak** [comment]
Is there a reason of making the script universal, apart from convenience when debugging? Personally, I always switch to the stage directory and submit the script from there. The documentation also states:

> Each regression test is executed in a “sandbox”; all of its resources (source files, input data etc.) are copied over to a stage directory (if the directory preexists, it will be wiped out) and executed from there. This will also be the working directory for the test.

So in order to replicate what ReFrame does, you have to switch to the stage directory, cos this is its working directory.

**Comment by vkarak** [comment]
I think that explicitly putting a `cd` would perhaps create more problems in the future in reasoning about the behaviour of the generated script. Currently, we can say that the generated script has the following structure:

```bash
#!/bin/bash -l
{job_scheduler_preamble}
{environment_load_commands}
{pre_run}
{parallel_run}
{post_run}
```

And it is launched from the stage directory of the test. I think, this is enough to reason about its behaviour. Putting a `cd` somewhere could ruin this logic if sb wants to explicitly pass the `--workdir` option (for whatever) reason or `cd` in the `pre_run`.

**Comment by victorusu** [comment]
I think that you are completely right! I missed the point here.  The invariant clear. 
We should not emit any `cd` command.
