### ISSUE TITLE
num_tasks in the performance logs and notification of failed tests as well

### ISSUE THREAD

**Issue by computingdolas** [eth-cscs/reframe#915]
Hi Guys, 
I would suggest having number of CPU tasks also in the performance logging -- because it becomes very difficult to track the performance variation if due to change in the number of CPUs assigned. 

Also it would be nice if we could log failed test over time. 

Let me know what you guys think about this. 

Best Regards,
Sagar

**Comment by vkarak** [comment]
@computingdolas I guess you are using flexible tests, right?

**Comment by computingdolas** [comment]
No, I am using simple tests.

**Comment by vkarak** [comment]
Perhaps we should extend the logging formatting mechanism internally, so that any field from a regression test could be logged.

**Comment by computingdolas** [comment]
Yes, that could be a solution.

**Comment by vkarak** [comment]
We need also to print the `num_tasks` in the performance report when a flexible task is run.

**Comment by vkarak** [comment]
Fixed in #976. 

@computingdolas I suggest opening a separate issue for the following with some more details on what you would like to see:

> Also it would be nice if we could log failed test over time.
